// trace:FR-MEG | ai:claude
//! Magnetoencephalography (MEG) Signal Processor
//!
//! MEG measures the extremely weak magnetic fields (femtotesla range) generated by
//! neuronal electrical activity in the brain using superconducting quantum interference
//! device (SQUID) sensors. This module provides a complete MEG signal processing
//! pipeline including:
//!
//! - **Forward modeling**: Computing predicted sensor measurements from current dipole
//!   sources using the Biot-Savart law for magnetic dipoles.
//! - **Source localization**: Dipole fitting via grid search, minimum norm estimation
//!   (MNE), LCMV beamforming, and MUSIC pseudo-spectrum scanning.
//! - **Signal preprocessing**: Bandpass filtering, power-line notch filtering, signal
//!   space projection (SSP) for artifact removal, spatial covariance estimation, and
//!   data whitening.
//! - **Connectivity analysis**: Magnitude-squared coherence, imaginary coherence
//!   (robust to volume conduction), and phase transfer entropy for directed
//!   connectivity.
//!
//! # Physical Background
//!
//! Neuronal currents (primarily post-synaptic potentials in pyramidal cells) produce
//! magnetic fields on the order of 50-500 femtotesla (fT) at the scalp surface.
//! Modern MEG systems use 100-300+ SQUID magnetometers/gradiometers with noise floors
//! of ~3-5 fT/sqrt(Hz), enabling non-invasive brain imaging with millisecond temporal
//! resolution.
//!
//! The magnetic field from a current dipole at position **r_q** with moment **Q** is
//! given by the Biot-Savart law:
//!
//! **B**(**r**) = (mu_0 / 4 pi) * (3(**Q** . **r_hat**)**r_hat** - **Q**) / |**r** - **r_q**|^3
//!
//! where mu_0 = 4 pi x 10^-7 T m/A is the permeability of free space.
//!
//! # Applications
//!
//! - Epilepsy focus localization for pre-surgical planning
//! - Functional brain mapping (somatosensory, auditory, visual cortex)
//! - Brain-computer interfaces (BCI)
//! - Cognitive neuroscience research
//! - Resting-state connectivity analysis

use std::f64::consts::PI;

/// Permeability of free space in T*m/A (4 pi x 10^-7).
pub const MU_0: f64 = 4.0 * PI * 1e-7;

/// Configuration for an MEG sensor array and acquisition parameters.
///
/// Typical MEG systems have 102 magnetometers (Elekta/MEGIN Triux) or up to 306
/// channels (102 magnetometers + 204 planar gradiometers). Sample rates are
/// commonly 1000 Hz for clinical and up to 5000 Hz for research.
#[derive(Clone, Debug)]
pub struct MegConfig {
    /// Sampling rate in Hz (typically 1000-5000).
    pub sample_rate_hz: f64,
    /// Number of sensor channels (typically 102-306).
    pub num_channels: usize,
    /// 3D positions of each sensor in meters, shape [num_channels][3].
    pub sensor_positions: Vec<[f64; 3]>,
    /// Unit normal orientation vector of each sensor, shape [num_channels][3].
    pub sensor_orientations: Vec<[f64; 3]>,
    /// Sensor noise level in femtotesla per sqrt(Hz), typically 3-5 fT/sqrt(Hz).
    pub noise_level_ft: f64,
}

/// A current dipole source representing localized neuronal activity.
///
/// In MEG, brain activity is often modeled as an equivalent current dipole (ECD)
/// characterized by a position in 3D space and a moment vector. The moment direction
/// indicates the orientation of the net current flow, and its magnitude is measured
/// in ampere-meters (Am), typically on the order of 10-100 nAm for evoked responses.
#[derive(Clone, Debug)]
pub struct DipoleSource {
    /// Position of the dipole in meters [x, y, z].
    pub position: [f64; 3],
    /// Dipole moment in Am [Qx, Qy, Qz].
    pub moment: [f64; 3],
    /// Goodness of fit (0.0 to 1.0), indicating how well the dipole model
    /// explains the measured data. Values > 0.9 are typically considered good fits.
    pub goodness_of_fit: f64,
}

/// Core MEG signal processing engine.
///
/// Provides forward modeling (predicting sensor measurements from dipole sources)
/// and inverse solutions (estimating sources from measurements). The forward model
/// uses the Biot-Savart law for magnetic dipoles in a spherical head model
/// approximation.
pub struct MegProcessor {
    config: MegConfig,
}

impl MegProcessor {
    /// Creates a new MEG processor with the given configuration.
    ///
    /// # Arguments
    /// * `config` - MEG system configuration including sensor geometry and noise level.
    pub fn new(config: MegConfig) -> Self {
        Self { config }
    }

    /// Returns a reference to the processor configuration.
    pub fn config(&self) -> &MegConfig {
        &self.config
    }

    /// Computes the magnetic field component along a sensor's orientation axis
    /// produced by a current dipole at a given position.
    ///
    /// Uses the magnetic dipole approximation of the Biot-Savart law:
    ///
    /// B_sensor = (mu_0 / (4 pi r^3)) * [3(Q . r_hat)(r_hat . n) - (Q . n)]
    ///
    /// where:
    /// - Q is the dipole moment vector
    /// - r_hat is the unit vector from dipole to sensor
    /// - n is the sensor orientation (normal) vector
    /// - r is the distance from dipole to sensor
    ///
    /// # Arguments
    /// * `dipole_pos` - Position of the current dipole [x, y, z] in meters.
    /// * `dipole_moment` - Dipole moment [Qx, Qy, Qz] in ampere-meters.
    /// * `sensor_pos` - Position of the sensor [x, y, z] in meters.
    /// * `sensor_orient` - Unit orientation vector of the sensor.
    ///
    /// # Returns
    /// The magnetic field component along the sensor orientation in Tesla.
    pub fn magnetic_dipole_field(
        dipole_pos: [f64; 3],
        dipole_moment: [f64; 3],
        sensor_pos: [f64; 3],
        sensor_orient: [f64; 3],
    ) -> f64 {
        // Displacement vector from dipole to sensor
        let r = [
            sensor_pos[0] - dipole_pos[0],
            sensor_pos[1] - dipole_pos[1],
            sensor_pos[2] - dipole_pos[2],
        ];

        let r_mag_sq = r[0] * r[0] + r[1] * r[1] + r[2] * r[2];
        let r_mag = r_mag_sq.sqrt();

        if r_mag < 1e-15 {
            return 0.0;
        }

        let r_hat = [r[0] / r_mag, r[1] / r_mag, r[2] / r_mag];

        // Q . r_hat
        let q_dot_rhat = dipole_moment[0] * r_hat[0]
            + dipole_moment[1] * r_hat[1]
            + dipole_moment[2] * r_hat[2];

        // r_hat . n (sensor orientation)
        let rhat_dot_n = r_hat[0] * sensor_orient[0]
            + r_hat[1] * sensor_orient[1]
            + r_hat[2] * sensor_orient[2];

        // Q . n
        let q_dot_n = dipole_moment[0] * sensor_orient[0]
            + dipole_moment[1] * sensor_orient[1]
            + dipole_moment[2] * sensor_orient[2];

        let r_cubed = r_mag * r_mag * r_mag;
        let prefactor = MU_0 / (4.0 * PI * r_cubed);

        prefactor * (3.0 * q_dot_rhat * rhat_dot_n - q_dot_n)
    }

    /// Computes the forward model: predicted sensor measurements for a given dipole.
    ///
    /// For each sensor in the array, computes the magnetic field component along
    /// the sensor's orientation axis using the Biot-Savart dipole field formula.
    ///
    /// # Arguments
    /// * `source` - The current dipole source.
    /// * `sensor_positions` - Positions of all sensors [x, y, z] in meters.
    /// * `sensor_orientations` - Unit orientation vectors of all sensors.
    ///
    /// # Returns
    /// A vector of predicted field values (Tesla) at each sensor.
    pub fn forward_model(
        source: &DipoleSource,
        sensor_positions: &[[f64; 3]],
        sensor_orientations: &[[f64; 3]],
    ) -> Vec<f64> {
        sensor_positions
            .iter()
            .zip(sensor_orientations.iter())
            .map(|(pos, orient)| {
                Self::magnetic_dipole_field(source.position, source.moment, *pos, *orient)
            })
            .collect()
    }

    /// Fits a single equivalent current dipole (ECD) to sensor measurements
    /// using grid search over candidate positions with optimal moment estimation.
    ///
    /// For each grid point, the optimal dipole moment is computed analytically
    /// by solving the least-squares problem. The grid point yielding the highest
    /// goodness-of-fit is selected.
    ///
    /// The goodness of fit (GOF) is defined as:
    ///   GOF = 1 - ||m - m_pred||^2 / ||m||^2
    ///
    /// # Arguments
    /// * `measurements` - Observed sensor data vector (one value per sensor).
    /// * `sensor_positions` - 3D positions of sensors.
    /// * `sensor_orientations` - Unit orientation vectors of sensors.
    /// * `grid` - Candidate dipole positions to search over.
    ///
    /// # Returns
    /// The best-fitting `DipoleSource` from the grid search.
    pub fn dipole_fit(
        measurements: &[f64],
        sensor_positions: &[[f64; 3]],
        sensor_orientations: &[[f64; 3]],
        grid: &[[f64; 3]],
    ) -> DipoleSource {
        let n_sensors = measurements.len();
        let meas_power: f64 = measurements.iter().map(|m| m * m).sum();

        let mut best_gof = f64::NEG_INFINITY;
        let mut best_source = DipoleSource {
            position: [0.0; 3],
            moment: [0.0; 3],
            goodness_of_fit: 0.0,
        };

        for grid_pos in grid {
            // Build lead field matrix columns for x, y, z dipole components at this position
            // L is n_sensors x 3
            let mut lead_field = vec![[0.0f64; 3]; n_sensors];
            for (i, (sp, so)) in sensor_positions
                .iter()
                .zip(sensor_orientations.iter())
                .enumerate()
            {
                lead_field[i][0] =
                    Self::magnetic_dipole_field(*grid_pos, [1.0, 0.0, 0.0], *sp, *so);
                lead_field[i][1] =
                    Self::magnetic_dipole_field(*grid_pos, [0.0, 1.0, 0.0], *sp, *so);
                lead_field[i][2] =
                    Self::magnetic_dipole_field(*grid_pos, [0.0, 0.0, 1.0], *sp, *so);
            }

            // Solve L^T L q = L^T m for optimal moment q (3x3 system)
            let mut ltl = [[0.0f64; 3]; 3];
            let mut ltm = [0.0f64; 3];

            for i in 0..n_sensors {
                for j in 0..3 {
                    ltm[j] += lead_field[i][j] * measurements[i];
                    for k in 0..3 {
                        ltl[j][k] += lead_field[i][j] * lead_field[i][k];
                    }
                }
            }

            // Solve 3x3 system using Cramer's rule
            let moment = solve_3x3(&ltl, &ltm);

            // Compute predicted measurements
            let mut residual_power = 0.0;
            for i in 0..n_sensors {
                let predicted = lead_field[i][0] * moment[0]
                    + lead_field[i][1] * moment[1]
                    + lead_field[i][2] * moment[2];
                let diff = measurements[i] - predicted;
                residual_power += diff * diff;
            }

            let gof = if meas_power > 1e-30 {
                1.0 - residual_power / meas_power
            } else {
                0.0
            };

            if gof > best_gof {
                best_gof = gof;
                best_source = DipoleSource {
                    position: *grid_pos,
                    moment,
                    goodness_of_fit: gof,
                };
            }
        }

        best_source
    }

    /// Computes the L2 minimum norm estimate (MNE) of distributed source currents.
    ///
    /// The minimum norm solution minimizes ||J||^2 subject to L*J = m, with
    /// Tikhonov regularization:
    ///
    ///   J = L^T (L L^T + lambda I)^{-1} m
    ///
    /// where L is the lead field matrix, m is the measurement vector, and lambda
    /// controls the regularization strength.
    ///
    /// # Arguments
    /// * `measurements` - Observed sensor data (length = num_sensors).
    /// * `lead_field` - Lead field matrix, each element is a column of L (length = num_sensors).
    ///   The outer Vec has length = num_source_components, each inner Vec has length = num_sensors.
    /// * `lambda` - Tikhonov regularization parameter (typically 0.01-0.1 times the
    ///   largest eigenvalue of L*L^T).
    ///
    /// # Returns
    /// Estimated source amplitudes (one per lead field column).
    pub fn minimum_norm_estimate(
        measurements: &[f64],
        lead_field: &[Vec<f64>],
        lambda: f64,
    ) -> Vec<f64> {
        let n_sensors = measurements.len();
        let n_sources = lead_field.len();

        if n_sensors == 0 || n_sources == 0 {
            return vec![0.0; n_sources];
        }

        // Compute G = L L^T + lambda I  (n_sensors x n_sensors)
        let mut g = vec![vec![0.0f64; n_sensors]; n_sensors];

        for src in 0..n_sources {
            for i in 0..n_sensors {
                for j in 0..n_sensors {
                    g[i][j] += lead_field[src][i] * lead_field[src][j];
                }
            }
        }

        // Add regularization
        for i in 0..n_sensors {
            g[i][i] += lambda;
        }

        // Solve G * x = m using Cholesky-like approach (symmetric positive definite)
        // Use Gaussian elimination with partial pivoting for robustness
        let x = solve_linear_system(&g, measurements);

        // J = L^T * x
        let mut result = vec![0.0f64; n_sources];
        for (s, lf_col) in lead_field.iter().enumerate() {
            for i in 0..n_sensors {
                result[s] += lf_col[i] * x[i];
            }
        }

        result
    }

    /// Computes LCMV (Linearly Constrained Minimum Variance) beamformer power
    /// at a single brain location.
    ///
    /// The LCMV beamformer spatial filter is:
    ///   w = C^{-1} l / (l^T C^{-1} l)
    ///
    /// The source power at the location is:
    ///   P = w^T C w = 1 / (l^T C^{-1} l)
    ///
    /// where C is the data covariance matrix and l is the lead field vector at
    /// the target location.
    ///
    /// # Arguments
    /// * `data` - Multi-channel time series data, shape [num_channels][num_samples].
    /// * `lead_field_at_point` - Lead field vector at the target location (length = num_channels).
    ///
    /// # Returns
    /// Estimated source power at the target location.
    pub fn beamformer_lcmv(data: &[Vec<f64>], lead_field_at_point: &[f64]) -> f64 {
        let n_channels = data.len();
        if n_channels == 0 {
            return 0.0;
        }

        // Compute covariance matrix
        let mut cov = SignalPreprocessor::covariance_matrix(data);

        // Add diagonal loading for numerical stability (1% of trace)
        let trace: f64 = (0..n_channels).map(|i| cov[i][i]).sum();
        let reg = trace * 0.01 / n_channels as f64;
        if reg > 0.0 {
            for i in 0..n_channels {
                cov[i][i] += reg;
            }
        }

        // Solve C * y = l for y = C^{-1} l
        let y = solve_linear_system(&cov, lead_field_at_point);

        // l^T C^{-1} l = l^T y
        let lt_cinv_l: f64 = lead_field_at_point
            .iter()
            .zip(y.iter())
            .map(|(l, yi)| l * yi)
            .sum();

        if lt_cinv_l.abs() < 1e-300 {
            return 0.0;
        }

        1.0 / lt_cinv_l
    }
}

/// MEG signal preprocessing utilities.
///
/// Provides temporal and spatial filtering operations commonly applied to raw
/// MEG data before source analysis, including bandpass filtering for frequency
/// band extraction, power-line notch filtering, signal space projection for
/// environmental noise removal, and spatial covariance estimation.
pub struct SignalPreprocessor;

impl SignalPreprocessor {
    /// Applies a simple IIR bandpass filter to a single-channel signal.
    ///
    /// Uses cascaded second-order biquad sections: one highpass (Butterworth)
    /// and one lowpass (Butterworth) to create a bandpass characteristic.
    ///
    /// # Arguments
    /// * `signal` - Input time series.
    /// * `low_hz` - Lower cutoff frequency in Hz.
    /// * `high_hz` - Upper cutoff frequency in Hz.
    /// * `sample_rate` - Sampling rate in Hz.
    ///
    /// # Returns
    /// Bandpass-filtered signal of the same length.
    pub fn bandpass(signal: &[f64], low_hz: f64, high_hz: f64, sample_rate: f64) -> Vec<f64> {
        if signal.is_empty() {
            return vec![];
        }

        // Apply highpass then lowpass using simple 2nd order IIR sections
        let hp = biquad_highpass(signal, low_hz, sample_rate);
        biquad_lowpass(&hp, high_hz, sample_rate)
    }

    /// Applies a notch (band-reject) filter to remove a specific frequency,
    /// typically 50 Hz or 60 Hz power-line interference.
    ///
    /// Uses a second-order IIR notch filter with configurable Q factor.
    ///
    /// # Arguments
    /// * `signal` - Input/output time series (modified in place).
    /// * `freq_hz` - Center frequency to notch out in Hz.
    /// * `sample_rate` - Sampling rate in Hz.
    /// * `q` - Quality factor controlling notch width (higher = narrower).
    pub fn notch_filter(signal: &mut Vec<f64>, freq_hz: f64, sample_rate: f64, q: f64) {
        if signal.is_empty() {
            return;
        }

        let w0 = 2.0 * PI * freq_hz / sample_rate;
        let alpha = w0.sin() / (2.0 * q);
        let cos_w0 = w0.cos();

        // Notch filter coefficients
        let b0 = 1.0;
        let b1 = -2.0 * cos_w0;
        let b2 = 1.0;
        let a0 = 1.0 + alpha;
        let a1 = -2.0 * cos_w0;
        let a2 = 1.0 - alpha;

        // Normalize
        let b0 = b0 / a0;
        let b1 = b1 / a0;
        let b2 = b2 / a0;
        let a1 = a1 / a0;
        let a2 = a2 / a0;

        let mut x1 = 0.0;
        let mut x2 = 0.0;
        let mut y1 = 0.0;
        let mut y2 = 0.0;

        for sample in signal.iter_mut() {
            let x0 = *sample;
            let y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;
            x2 = x1;
            x1 = x0;
            y2 = y1;
            y1 = y0;
            *sample = y0;
        }
    }

    /// Applies Signal Space Projection (SSP) for artifact removal.
    ///
    /// Projects data away from artifact subspace defined by projector vectors.
    /// Each projector represents a spatial pattern of artifact (e.g., heartbeat,
    /// eye blink). The projection operator is:
    ///
    ///   P = I - sum_k (p_k p_k^T / ||p_k||^2)
    ///
    /// # Arguments
    /// * `data` - Multi-channel data [num_channels][num_samples], modified in place.
    /// * `projectors` - Artifact spatial patterns, each of length num_channels.
    pub fn ssp_projection(data: &mut Vec<Vec<f64>>, projectors: &[Vec<f64>]) {
        let n_channels = data.len();
        if n_channels == 0 || projectors.is_empty() {
            return;
        }

        let n_samples = data[0].len();

        // Build projection matrix P = I - sum(p_k p_k^T / ||p_k||^2)
        let mut proj_matrix = vec![vec![0.0f64; n_channels]; n_channels];

        // Start with identity
        for i in 0..n_channels {
            proj_matrix[i][i] = 1.0;
        }

        // Subtract outer products of normalized projectors
        for p in projectors {
            let norm_sq: f64 = p.iter().map(|x| x * x).sum();
            if norm_sq < 1e-30 {
                continue;
            }
            for i in 0..n_channels.min(p.len()) {
                for j in 0..n_channels.min(p.len()) {
                    proj_matrix[i][j] -= p[i] * p[j] / norm_sq;
                }
            }
        }

        // Apply projection: data_new = P * data
        let mut temp = vec![0.0f64; n_channels];
        for s in 0..n_samples {
            // Gather column
            for ch in 0..n_channels {
                temp[ch] = data[ch][s];
            }
            // Matrix-vector multiply
            for ch in 0..n_channels {
                let mut val = 0.0;
                for k in 0..n_channels {
                    val += proj_matrix[ch][k] * temp[k];
                }
                data[ch][s] = val;
            }
        }
    }

    /// Computes the spatial covariance matrix from multi-channel data.
    ///
    /// C = (1/T) * X X^T
    ///
    /// where X is the [channels x samples] data matrix.
    ///
    /// # Arguments
    /// * `data` - Multi-channel time series [num_channels][num_samples].
    ///
    /// # Returns
    /// Covariance matrix [num_channels][num_channels].
    pub fn covariance_matrix(data: &[Vec<f64>]) -> Vec<Vec<f64>> {
        let n_channels = data.len();
        if n_channels == 0 {
            return vec![];
        }
        let n_samples = data[0].len();
        if n_samples == 0 {
            return vec![vec![0.0; n_channels]; n_channels];
        }

        let mut cov = vec![vec![0.0f64; n_channels]; n_channels];

        for i in 0..n_channels {
            for j in i..n_channels {
                let mut sum = 0.0;
                for s in 0..n_samples {
                    sum += data[i][s] * data[j][s];
                }
                let val = sum / n_samples as f64;
                cov[i][j] = val;
                cov[j][i] = val;
            }
        }

        cov
    }

    /// Computes a whitening matrix from a covariance matrix.
    ///
    /// The whitening matrix W transforms data such that the covariance of
    /// W*X is the identity matrix. Uses eigendecomposition:
    ///
    ///   W = D^{-1/2} E^T
    ///
    /// where C = E D E^T is the eigendecomposition of the covariance.
    ///
    /// For numerical stability, a simple regularized inverse square root is used.
    ///
    /// # Arguments
    /// * `covariance` - Spatial covariance matrix [n x n].
    ///
    /// # Returns
    /// Whitening matrix [n x n].
    pub fn whitening_matrix(covariance: &[Vec<f64>]) -> Vec<Vec<f64>> {
        let n = covariance.len();
        if n == 0 {
            return vec![];
        }

        // Use Jacobi eigendecomposition for symmetric matrix
        let (eigenvalues, eigenvectors) = jacobi_eigen(covariance);

        // W = D^{-1/2} * E^T (each row of W is eigenvector / sqrt(eigenvalue))
        let mut w = vec![vec![0.0f64; n]; n];

        for i in 0..n {
            let scale = if eigenvalues[i] > 1e-15 {
                1.0 / eigenvalues[i].sqrt()
            } else {
                0.0
            };
            for j in 0..n {
                w[i][j] = eigenvectors[j][i] * scale;
            }
        }

        w
    }
}

/// Source localization algorithms for MEG.
///
/// Provides methods to estimate the location of brain activity from sensor
/// measurements, including exhaustive dipole scanning, MUSIC pseudo-spectrum,
/// and localization error computation.
pub struct SourceLocalizer;

impl SourceLocalizer {
    /// Performs dipole scanning over a grid of candidate positions.
    ///
    /// For each grid point, computes the optimal dipole moment and goodness of fit.
    /// The GOF at each point indicates how well a single dipole at that location
    /// can explain the measured data.
    ///
    /// # Arguments
    /// * `measurements` - Observed sensor data.
    /// * `grid` - Candidate dipole positions.
    /// * `sensor_positions` - Sensor positions.
    /// * `sensor_orientations` - Sensor orientations.
    ///
    /// # Returns
    /// Vector of (goodness_of_fit, position) tuples sorted by descending GOF.
    pub fn dipole_scanning(
        measurements: &[f64],
        grid: &[[f64; 3]],
        sensor_positions: &[[f64; 3]],
        sensor_orientations: &[[f64; 3]],
    ) -> Vec<(f64, [f64; 3])> {
        let n_sensors = measurements.len();
        let meas_power: f64 = measurements.iter().map(|m| m * m).sum();

        let mut results: Vec<(f64, [f64; 3])> = grid
            .iter()
            .map(|grid_pos| {
                // Build lead field for this position
                let mut lf = vec![[0.0f64; 3]; n_sensors];
                for (i, (sp, so)) in sensor_positions
                    .iter()
                    .zip(sensor_orientations.iter())
                    .enumerate()
                {
                    lf[i][0] =
                        MegProcessor::magnetic_dipole_field(*grid_pos, [1.0, 0.0, 0.0], *sp, *so);
                    lf[i][1] =
                        MegProcessor::magnetic_dipole_field(*grid_pos, [0.0, 1.0, 0.0], *sp, *so);
                    lf[i][2] =
                        MegProcessor::magnetic_dipole_field(*grid_pos, [0.0, 0.0, 1.0], *sp, *so);
                }

                // Optimal moment via L^T L q = L^T m
                let mut ltl = [[0.0f64; 3]; 3];
                let mut ltm = [0.0f64; 3];
                for i in 0..n_sensors {
                    for j in 0..3 {
                        ltm[j] += lf[i][j] * measurements[i];
                        for k in 0..3 {
                            ltl[j][k] += lf[i][j] * lf[i][k];
                        }
                    }
                }
                let moment = solve_3x3(&ltl, &ltm);

                // GOF
                let mut residual_power = 0.0;
                for i in 0..n_sensors {
                    let pred =
                        lf[i][0] * moment[0] + lf[i][1] * moment[1] + lf[i][2] * moment[2];
                    let diff = measurements[i] - pred;
                    residual_power += diff * diff;
                }

                let gof = if meas_power > 1e-30 {
                    1.0 - residual_power / meas_power
                } else {
                    0.0
                };

                (gof, *grid_pos)
            })
            .collect();

        results.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
        results
    }

    /// Computes MUSIC (MUltiple SIgnal Classification) pseudo-spectrum for
    /// source localization.
    ///
    /// MUSIC exploits the orthogonality between the signal subspace and noise
    /// subspace to form a pseudo-spectrum that peaks at source locations.
    ///
    ///   P_MUSIC(r) = 1 / (l(r)^T E_n E_n^T l(r))
    ///
    /// where E_n are the noise-subspace eigenvectors of the covariance matrix.
    ///
    /// # Arguments
    /// * `covariance` - Spatial covariance matrix [n_channels x n_channels].
    /// * `lead_fields` - Lead field vectors for each grid point. lead_fields[i] is a
    ///   Vec of Vec<f64>, where each inner Vec is one orientation component (length n_channels).
    /// * `num_sources` - Estimated number of active sources.
    ///
    /// # Returns
    /// MUSIC pseudo-spectrum value at each grid point.
    pub fn music_localization(
        covariance: &[Vec<f64>],
        lead_fields: &[Vec<Vec<f64>>],
        num_sources: usize,
    ) -> Vec<f64> {
        let n = covariance.len();
        if n == 0 || lead_fields.is_empty() {
            return vec![];
        }

        // Eigendecomposition of covariance
        let (eigenvalues, eigenvectors) = jacobi_eigen(covariance);

        // Sort eigenvalues descending, get noise subspace
        let mut indices: Vec<usize> = (0..n).collect();
        indices.sort_by(|&a, &b| {
            eigenvalues[b]
                .partial_cmp(&eigenvalues[a])
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        // Noise subspace: eigenvectors corresponding to smallest eigenvalues
        let noise_start = num_sources.min(n);
        let noise_indices = &indices[noise_start..];

        lead_fields
            .iter()
            .map(|lf_at_point| {
                // For each orientation component, compute projection onto noise subspace
                // Use the first lead field component (simplification for scalar case)
                let l = if lf_at_point.is_empty() {
                    return 0.0;
                } else {
                    &lf_at_point[0]
                };

                if l.len() != n {
                    return 0.0;
                }

                // Compute l^T E_n E_n^T l
                let mut noise_proj = 0.0;
                for &ni in noise_indices {
                    // Project l onto this noise eigenvector
                    let mut dot = 0.0;
                    for j in 0..n {
                        dot += l[j] * eigenvectors[j][ni];
                    }
                    noise_proj += dot * dot;
                }

                if noise_proj < 1e-30 {
                    1e15 // Very large (source location)
                } else {
                    1.0 / noise_proj
                }
            })
            .collect()
    }

    /// Computes the localization error between true and estimated dipole positions.
    ///
    /// # Arguments
    /// * `true_pos` - True dipole position [x, y, z] in meters.
    /// * `estimated_pos` - Estimated dipole position [x, y, z] in meters.
    ///
    /// # Returns
    /// Euclidean distance error in millimeters.
    pub fn equivalent_current_dipole_error(true_pos: [f64; 3], estimated_pos: [f64; 3]) -> f64 {
        let dx = true_pos[0] - estimated_pos[0];
        let dy = true_pos[1] - estimated_pos[1];
        let dz = true_pos[2] - estimated_pos[2];
        (dx * dx + dy * dy + dz * dz).sqrt() * 1000.0 // Convert m to mm
    }
}

/// Brain connectivity analysis from MEG data.
///
/// Provides spectral connectivity measures including coherence, imaginary
/// coherence (robust to volume conduction artifacts), and phase transfer
/// entropy for directed information flow estimation.
pub struct ConnectivityAnalyzer;

impl ConnectivityAnalyzer {
    /// Computes magnitude-squared coherence between two channels.
    ///
    /// Coherence measures the linear relationship between two signals at each
    /// frequency. It is defined as:
    ///
    ///   Coh(f) = |S_xy(f)|^2 / (S_xx(f) * S_yy(f))
    ///
    /// Values range from 0 (no linear relationship) to 1 (perfect linear
    /// relationship). Note that coherence is sensitive to volume conduction.
    ///
    /// # Arguments
    /// * `channel1` - First channel time series.
    /// * `channel2` - Second channel time series.
    /// * `sample_rate` - Sampling rate in Hz.
    /// * `fft_size` - FFT length for spectral estimation.
    ///
    /// # Returns
    /// Vector of (frequency_hz, coherence) tuples for positive frequencies.
    pub fn coherence(
        channel1: &[f64],
        channel2: &[f64],
        sample_rate: f64,
        fft_size: usize,
    ) -> Vec<(f64, f64)> {
        let total_len = channel1.len().min(channel2.len());
        if total_len == 0 || fft_size == 0 {
            return vec![];
        }

        let n_freqs = fft_size / 2 + 1;
        let freq_resolution = sample_rate / fft_size as f64;

        // Welch averaging with 50% overlap
        let step = fft_size / 2;
        let step = if step == 0 { 1 } else { step };
        let mut avg_sxx = vec![0.0f64; n_freqs];
        let mut avg_syy = vec![0.0f64; n_freqs];
        let mut avg_sxy_re = vec![0.0f64; n_freqs];
        let mut avg_sxy_im = vec![0.0f64; n_freqs];
        let mut n_segments = 0;

        let mut offset = 0;
        while offset + fft_size <= total_len {
            let seg1 = &channel1[offset..offset + fft_size];
            let seg2 = &channel2[offset..offset + fft_size];
            let (sxx, syy, sxy_re, sxy_im) =
                cross_spectral_density(seg1, seg2, sample_rate, fft_size);
            for i in 0..n_freqs {
                avg_sxx[i] += sxx[i];
                avg_syy[i] += syy[i];
                avg_sxy_re[i] += sxy_re[i];
                avg_sxy_im[i] += sxy_im[i];
            }
            n_segments += 1;
            offset += step;
        }

        if n_segments == 0 {
            // Fall back to single segment using available data
            let seg_len = total_len.min(fft_size);
            let (sxx, syy, sxy_re, sxy_im) =
                cross_spectral_density(&channel1[..seg_len], &channel2[..seg_len], sample_rate, fft_size);
            for i in 0..n_freqs {
                avg_sxx[i] = sxx[i];
                avg_syy[i] = syy[i];
                avg_sxy_re[i] = sxy_re[i];
                avg_sxy_im[i] = sxy_im[i];
            }
            n_segments = 1;
        }

        let mut result = Vec::with_capacity(n_freqs);
        for i in 0..n_freqs {
            let freq = i as f64 * freq_resolution;
            let denom = avg_sxx[i] * avg_syy[i];
            let coh = if denom > 1e-30 {
                (avg_sxy_re[i] * avg_sxy_re[i] + avg_sxy_im[i] * avg_sxy_im[i]) / denom
            } else {
                0.0
            };
            result.push((freq, coh.min(1.0)));
        }

        result
    }

    /// Computes imaginary coherence between two channels.
    ///
    /// Imaginary coherence uses only the imaginary part of the cross-spectrum,
    /// making it robust to volume conduction artifacts (which produce
    /// instantaneous, zero-lag correlations that are purely real-valued in the
    /// cross-spectrum).
    ///
    ///   ImCoh(f) = |Im(S_xy(f))| / sqrt(S_xx(f) * S_yy(f))
    ///
    /// # Arguments
    /// * `channel1` - First channel time series.
    /// * `channel2` - Second channel time series.
    /// * `sample_rate` - Sampling rate in Hz.
    /// * `fft_size` - FFT length.
    ///
    /// # Returns
    /// Vector of (frequency_hz, imaginary_coherence) tuples.
    pub fn imaginary_coherence(
        channel1: &[f64],
        channel2: &[f64],
        sample_rate: f64,
        fft_size: usize,
    ) -> Vec<(f64, f64)> {
        let total_len = channel1.len().min(channel2.len());
        if total_len == 0 || fft_size == 0 {
            return vec![];
        }

        let n_freqs = fft_size / 2 + 1;
        let freq_resolution = sample_rate / fft_size as f64;

        // Welch averaging with 50% overlap
        let step = fft_size / 2;
        let step = if step == 0 { 1 } else { step };
        let mut avg_sxx = vec![0.0f64; n_freqs];
        let mut avg_syy = vec![0.0f64; n_freqs];
        let mut avg_sxy_im = vec![0.0f64; n_freqs];
        let mut n_segments = 0;

        let mut offset = 0;
        while offset + fft_size <= total_len {
            let seg1 = &channel1[offset..offset + fft_size];
            let seg2 = &channel2[offset..offset + fft_size];
            let (sxx, syy, _sxy_re, sxy_im) =
                cross_spectral_density(seg1, seg2, sample_rate, fft_size);
            for i in 0..n_freqs {
                avg_sxx[i] += sxx[i];
                avg_syy[i] += syy[i];
                avg_sxy_im[i] += sxy_im[i];
            }
            n_segments += 1;
            offset += step;
        }

        if n_segments == 0 {
            let seg_len = total_len.min(fft_size);
            let (sxx, syy, _sxy_re, sxy_im) =
                cross_spectral_density(&channel1[..seg_len], &channel2[..seg_len], sample_rate, fft_size);
            for i in 0..n_freqs {
                avg_sxx[i] = sxx[i];
                avg_syy[i] = syy[i];
                avg_sxy_im[i] = sxy_im[i];
            }
        }

        let mut result = Vec::with_capacity(n_freqs);
        for i in 0..n_freqs {
            let freq = i as f64 * freq_resolution;
            let denom = (avg_sxx[i] * avg_syy[i]).sqrt();
            let icoh = if denom > 1e-30 {
                avg_sxy_im[i].abs() / denom
            } else {
                0.0
            };
            result.push((freq, icoh.min(1.0)));
        }

        result
    }

    /// Estimates phase transfer entropy from channel x to channel y.
    ///
    /// Transfer entropy quantifies the directed information flow from one time
    /// series to another by measuring the reduction in uncertainty about y's
    /// future given past values of x, beyond what is already known from y's past:
    ///
    ///   TE(x->y) = H(y_{t+1} | y_t) - H(y_{t+1} | y_t, x_{t-lag})
    ///
    /// This simplified implementation uses binned estimation of the conditional
    /// entropies.
    ///
    /// # Arguments
    /// * `x` - Source time series.
    /// * `y` - Target time series.
    /// * `lag` - Time lag (in samples) for the transfer entropy computation.
    ///
    /// # Returns
    /// Transfer entropy estimate in nats (non-negative).
    pub fn phase_transfer_entropy(x: &[f64], y: &[f64], lag: usize) -> f64 {
        let n = x.len().min(y.len());
        if n < lag + 2 {
            return 0.0;
        }

        let num_bins = 8;

        // Bin the signals
        let x_binned = bin_signal(x, num_bins);
        let y_binned = bin_signal(y, num_bins);

        let valid_len = n - lag - 1;
        if valid_len == 0 {
            return 0.0;
        }

        // Count joint and marginal distributions
        // We need: p(y_{t+1}, y_t, x_{t-lag}), p(y_{t+1}, y_t), p(y_t, x_{t-lag}), p(y_t)
        let mut count_yf_yp_x =
            vec![vec![vec![0usize; num_bins]; num_bins]; num_bins]; // [y_future][y_past][x_past]
        let mut count_yf_yp = vec![vec![0usize; num_bins]; num_bins]; // [y_future][y_past]
        let mut count_yp_x = vec![vec![0usize; num_bins]; num_bins]; // [y_past][x_past]
        let mut count_yp = vec![0usize; num_bins]; // [y_past]

        for t in lag..n - 1 {
            let y_future = y_binned[t + 1];
            let y_past = y_binned[t];
            let x_past = x_binned[t - lag];

            count_yf_yp_x[y_future][y_past][x_past] += 1;
            count_yf_yp[y_future][y_past] += 1;
            count_yp_x[y_past][x_past] += 1;
            count_yp[y_past] += 1;
        }

        let total = valid_len as f64;

        // TE = sum p(y_{t+1}, y_t, x_{t-lag}) * log[ p(y_{t+1}|y_t, x_{t-lag}) / p(y_{t+1}|y_t) ]
        //    = sum p(yf, yp, xp) * log[ p(yf, yp, xp) * p(yp) / (p(yf, yp) * p(yp, xp)) ]
        let mut te = 0.0;

        for yf in 0..num_bins {
            for yp in 0..num_bins {
                for xp in 0..num_bins {
                    let c_yf_yp_xp = count_yf_yp_x[yf][yp][xp];
                    if c_yf_yp_xp == 0 {
                        continue;
                    }
                    let c_yf_yp = count_yf_yp[yf][yp];
                    let c_yp_xp = count_yp_x[yp][xp];
                    let c_yp = count_yp[yp];

                    if c_yf_yp == 0 || c_yp_xp == 0 || c_yp == 0 {
                        continue;
                    }

                    let p_joint = c_yf_yp_xp as f64 / total;
                    let ratio = (c_yf_yp_xp as f64 * c_yp as f64)
                        / (c_yf_yp as f64 * c_yp_xp as f64);

                    if ratio > 0.0 {
                        te += p_joint * ratio.ln();
                    }
                }
            }
        }

        te.max(0.0) // Transfer entropy is non-negative
    }
}

// ============================================================
// Internal helper functions
// ============================================================

/// Solves a 3x3 linear system Ax = b using Cramer's rule.
fn solve_3x3(a: &[[f64; 3]; 3], b: &[f64; 3]) -> [f64; 3] {
    let det = a[0][0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
        - a[0][1] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
        + a[0][2] * (a[1][0] * a[2][1] - a[1][1] * a[2][0]);

    if det.abs() < 1e-30 {
        return [0.0; 3];
    }

    let inv_det = 1.0 / det;

    let x0 = (b[0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
        - a[0][1] * (b[1] * a[2][2] - a[1][2] * b[2])
        + a[0][2] * (b[1] * a[2][1] - a[1][1] * b[2]))
        * inv_det;

    let x1 = (a[0][0] * (b[1] * a[2][2] - a[1][2] * b[2])
        - b[0] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
        + a[0][2] * (a[1][0] * b[2] - b[1] * a[2][0]))
        * inv_det;

    let x2 = (a[0][0] * (a[1][1] * b[2] - b[1] * a[2][1])
        - a[0][1] * (a[1][0] * b[2] - b[1] * a[2][0])
        + b[0] * (a[1][0] * a[2][1] - a[1][1] * a[2][0]))
        * inv_det;

    [x0, x1, x2]
}

/// Solves a general n x n linear system Ax = b using Gaussian elimination with
/// partial pivoting and relative threshold.
fn solve_linear_system(a: &[Vec<f64>], b: &[f64]) -> Vec<f64> {
    let n = b.len();
    if n == 0 {
        return vec![];
    }

    // Augmented matrix
    let mut aug = vec![vec![0.0f64; n + 1]; n];
    for i in 0..n {
        for j in 0..n {
            aug[i][j] = a[i][j];
        }
        aug[i][n] = b[i];
    }

    // Compute a scale factor for relative pivoting
    let max_abs = a
        .iter()
        .flat_map(|row| row.iter())
        .map(|v| v.abs())
        .fold(0.0f64, f64::max);
    let tol = max_abs * 1e-14;
    let tol = if tol > 0.0 { tol } else { 1e-300 };

    // Forward elimination with partial pivoting
    for col in 0..n {
        // Find pivot
        let mut max_val = aug[col][col].abs();
        let mut max_row = col;
        for row in (col + 1)..n {
            let val = aug[row][col].abs();
            if val > max_val {
                max_val = val;
                max_row = row;
            }
        }

        if max_val < tol {
            continue; // Singular or near-singular relative to matrix scale
        }

        // Swap rows
        if max_row != col {
            aug.swap(col, max_row);
        }

        // Eliminate below
        let pivot = aug[col][col];
        for row in (col + 1)..n {
            let factor = aug[row][col] / pivot;
            for j in col..=n {
                aug[row][j] -= factor * aug[col][j];
            }
        }
    }

    // Back substitution
    let mut x = vec![0.0f64; n];
    for i in (0..n).rev() {
        let mut sum = aug[i][n];
        for j in (i + 1)..n {
            sum -= aug[i][j] * x[j];
        }
        if aug[i][i].abs() > tol {
            x[i] = sum / aug[i][i];
        }
    }

    x
}

/// Jacobi eigendecomposition for a real symmetric matrix.
/// Returns (eigenvalues, eigenvectors) where eigenvectors[i][j] is the i-th
/// component of the j-th eigenvector.
fn jacobi_eigen(matrix: &[Vec<f64>]) -> (Vec<f64>, Vec<Vec<f64>>) {
    let n = matrix.len();
    if n == 0 {
        return (vec![], vec![]);
    }

    // Working copy
    let mut a = vec![vec![0.0f64; n]; n];
    for i in 0..n {
        for j in 0..n {
            a[i][j] = matrix[i][j];
        }
    }

    // Eigenvector matrix (starts as identity)
    let mut v = vec![vec![0.0f64; n]; n];
    for i in 0..n {
        v[i][i] = 1.0;
    }

    let max_iter = 100 * n * n;

    for _ in 0..max_iter {
        // Find largest off-diagonal element
        let mut max_off = 0.0f64;
        let mut p = 0;
        let mut q = 1;

        for i in 0..n {
            for j in (i + 1)..n {
                let val = a[i][j].abs();
                if val > max_off {
                    max_off = val;
                    p = i;
                    q = j;
                }
            }
        }

        if max_off < 1e-12 {
            break;
        }

        // Compute rotation
        let diff = a[q][q] - a[p][p];
        let t = if diff.abs() < 1e-15 {
            1.0f64
        } else {
            let tau = diff / (2.0 * a[p][q]);
            let sign = if tau >= 0.0 { 1.0 } else { -1.0 };
            sign / (tau.abs() + (1.0 + tau * tau).sqrt())
        };

        let c = 1.0 / (1.0 + t * t).sqrt();
        let s = t * c;
        let tau_val = s / (1.0 + c);

        let apq = a[p][q];
        a[p][q] = 0.0;
        a[p][p] -= t * apq;
        a[q][q] += t * apq;

        // Update off-diagonal elements
        for r in 0..n {
            if r != p && r != q {
                let arp = a[r][p];
                let arq = a[r][q];
                a[r][p] = arp - s * (arq + tau_val * arp);
                a[p][r] = a[r][p];
                a[r][q] = arq + s * (arp - tau_val * arq);
                a[q][r] = a[r][q];
            }
        }

        // Update eigenvectors
        for r in 0..n {
            let vrp = v[r][p];
            let vrq = v[r][q];
            v[r][p] = vrp - s * (vrq + tau_val * vrp);
            v[r][q] = vrq + s * (vrp - tau_val * vrq);
        }
    }

    let eigenvalues: Vec<f64> = (0..n).map(|i| a[i][i]).collect();
    (eigenvalues, v)
}

/// Second-order Butterworth lowpass biquad filter.
fn biquad_lowpass(signal: &[f64], cutoff_hz: f64, sample_rate: f64) -> Vec<f64> {
    let w0 = 2.0 * PI * cutoff_hz / sample_rate;
    let alpha = w0.sin() / (2.0 * std::f64::consts::SQRT_2); // Q = 1/sqrt(2) for Butterworth
    let cos_w0 = w0.cos();

    let b0 = (1.0 - cos_w0) / 2.0;
    let b1 = 1.0 - cos_w0;
    let b2 = (1.0 - cos_w0) / 2.0;
    let a0 = 1.0 + alpha;
    let a1 = -2.0 * cos_w0;
    let a2 = 1.0 - alpha;

    apply_biquad(signal, b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)
}

/// Second-order Butterworth highpass biquad filter.
fn biquad_highpass(signal: &[f64], cutoff_hz: f64, sample_rate: f64) -> Vec<f64> {
    let w0 = 2.0 * PI * cutoff_hz / sample_rate;
    let alpha = w0.sin() / (2.0 * std::f64::consts::SQRT_2);
    let cos_w0 = w0.cos();

    let b0 = (1.0 + cos_w0) / 2.0;
    let b1 = -(1.0 + cos_w0);
    let b2 = (1.0 + cos_w0) / 2.0;
    let a0 = 1.0 + alpha;
    let a1 = -2.0 * cos_w0;
    let a2 = 1.0 - alpha;

    apply_biquad(signal, b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)
}

/// Applies a biquad filter (Direct Form I).
fn apply_biquad(signal: &[f64], b0: f64, b1: f64, b2: f64, a1: f64, a2: f64) -> Vec<f64> {
    let mut output = Vec::with_capacity(signal.len());
    let mut x1 = 0.0;
    let mut x2 = 0.0;
    let mut y1 = 0.0;
    let mut y2 = 0.0;

    for &x0 in signal {
        let y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;
        x2 = x1;
        x1 = x0;
        y2 = y1;
        y1 = y0;
        output.push(y0);
    }

    output
}

/// Simple DFT for small sizes (no external FFT dependency).
/// Returns (real, imag) arrays of length fft_size.
fn simple_dft(signal: &[f64], fft_size: usize) -> (Vec<f64>, Vec<f64>) {
    let mut real = vec![0.0f64; fft_size];
    let mut imag = vec![0.0f64; fft_size];

    let n = signal.len().min(fft_size);

    for k in 0..fft_size {
        for (t, &s) in signal.iter().take(n).enumerate() {
            let angle = -2.0 * PI * k as f64 * t as f64 / fft_size as f64;
            real[k] += s * angle.cos();
            imag[k] += s * angle.sin();
        }
    }

    (real, imag)
}

/// Computes cross-spectral density components between two signals.
/// Returns (Sxx, Syy, Sxy_real, Sxy_imag) for positive frequencies.
fn cross_spectral_density(
    x: &[f64],
    y: &[f64],
    _sample_rate: f64,
    fft_size: usize,
) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    let n = x.len().min(y.len()).min(fft_size);

    // Apply Hann window
    let mut x_win = vec![0.0f64; n];
    let mut y_win = vec![0.0f64; n];
    for i in 0..n {
        let w = 0.5 * (1.0 - (2.0 * PI * i as f64 / (n as f64 - 1.0)).cos());
        x_win[i] = x[i] * w;
        y_win[i] = y[i] * w;
    }

    let (xr, xi) = simple_dft(&x_win, fft_size);
    let (yr, yi) = simple_dft(&y_win, fft_size);

    let n_freqs = fft_size / 2 + 1;
    let mut sxx = Vec::with_capacity(n_freqs);
    let mut syy = Vec::with_capacity(n_freqs);
    let mut sxy_re = Vec::with_capacity(n_freqs);
    let mut sxy_im = Vec::with_capacity(n_freqs);

    for k in 0..n_freqs {
        sxx.push(xr[k] * xr[k] + xi[k] * xi[k]);
        syy.push(yr[k] * yr[k] + yi[k] * yi[k]);
        // Cross-spectrum: X * conj(Y) = (Xr + jXi)(Yr - jYi) = XrYr + XiYi + j(XiYr - XrYi)
        sxy_re.push(xr[k] * yr[k] + xi[k] * yi[k]);
        sxy_im.push(xi[k] * yr[k] - xr[k] * yi[k]);
    }

    (sxx, syy, sxy_re, sxy_im)
}

/// Bins a signal into discrete levels for histogram-based entropy estimation.
fn bin_signal(signal: &[f64], num_bins: usize) -> Vec<usize> {
    if signal.is_empty() {
        return vec![];
    }

    let min_val = signal.iter().cloned().fold(f64::INFINITY, f64::min);
    let max_val = signal.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let range = max_val - min_val;

    if range < 1e-15 {
        return vec![0; signal.len()];
    }

    signal
        .iter()
        .map(|&v| {
            let bin = ((v - min_val) / range * (num_bins as f64 - 1.0)).round() as usize;
            bin.min(num_bins - 1)
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a hemispherical sensor array (like an MEG helmet).
    /// Sensors are placed on concentric rings at different elevations, with
    /// orientations pointing radially inward toward the origin.
    fn test_sensor_array(n: usize, radius: f64) -> (Vec<[f64; 3]>, Vec<[f64; 3]>) {
        let mut positions = Vec::with_capacity(n);
        let mut orientations = Vec::with_capacity(n);

        // Distribute sensors on a hemisphere using a Fibonacci-like spiral
        let golden_ratio = (1.0 + 5.0_f64.sqrt()) / 2.0;

        for i in 0..n {
            // Elevation angle from 10 to 80 degrees (avoid poles)
            let phi = (1.0 - (i as f64 + 0.5) / n as f64) * 70.0_f64.to_radians()
                + 10.0_f64.to_radians();
            let theta = 2.0 * PI * i as f64 / golden_ratio;

            let x = radius * phi.sin() * theta.cos();
            let y = radius * phi.sin() * theta.sin();
            let z = radius * phi.cos();

            positions.push([x, y, z]);
            // Orientation pointing inward (toward origin)
            let norm = (x * x + y * y + z * z).sqrt();
            orientations.push([-x / norm, -y / norm, -z / norm]);
        }

        (positions, orientations)
    }

    /// Helper: create a test config.
    fn test_config(n_sensors: usize) -> MegConfig {
        let (positions, orientations) = test_sensor_array(n_sensors, 0.12);
        MegConfig {
            sample_rate_hz: 1000.0,
            num_channels: n_sensors,
            sensor_positions: positions,
            sensor_orientations: orientations,
            noise_level_ft: 5.0,
        }
    }

    // =====================================================
    // Constants and configuration tests
    // =====================================================

    #[test]
    fn test_mu_0_value() {
        let expected = 4.0 * PI * 1e-7;
        assert!((MU_0 - expected).abs() < 1e-20);
    }

    #[test]
    fn test_meg_config_creation() {
        let config = test_config(32);
        assert_eq!(config.num_channels, 32);
        assert_eq!(config.sensor_positions.len(), 32);
        assert_eq!(config.sensor_orientations.len(), 32);
        assert!((config.sample_rate_hz - 1000.0).abs() < 1e-10);
        assert!((config.noise_level_ft - 5.0).abs() < 1e-10);
    }

    #[test]
    fn test_dipole_source_creation() {
        let src = DipoleSource {
            position: [0.01, 0.02, 0.03],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 0.95,
        };
        assert!((src.position[0] - 0.01).abs() < 1e-15);
        assert!((src.goodness_of_fit - 0.95).abs() < 1e-15);
    }

    // =====================================================
    // Dipole field tests
    // =====================================================

    #[test]
    fn test_dipole_field_1_over_r_cubed_decay() {
        let dipole_pos = [0.0, 0.0, 0.0];
        let moment = [0.0, 0.0, 1e-9]; // z-oriented dipole
        let orient = [0.0, 0.0, 1.0]; // Sensor oriented along z

        // Measure at two distances along x-axis
        // For a z-dipole measured along z at a point on x-axis:
        // Q.rhat = 0, Q.n = 1e-9, so B = prefactor * (0 - Q.n) = -mu0/(4pi r^3) * Q_z
        let r1 = 0.05;
        let r2 = 0.10;

        let b1 = MegProcessor::magnetic_dipole_field(
            dipole_pos,
            moment,
            [r1, 0.0, 0.0],
            orient,
        );
        let b2 = MegProcessor::magnetic_dipole_field(
            dipole_pos,
            moment,
            [r2, 0.0, 0.0],
            orient,
        );

        // Both should be non-zero
        assert!(b1.abs() > 1e-20, "B1 should be non-zero, got {}", b1);
        assert!(b2.abs() > 1e-20, "B2 should be non-zero, got {}", b2);

        // B should scale as 1/r^3, so |B1|/|B2| ~ (r2/r1)^3 = 8
        let ratio = b1 / b2;
        assert!(
            (ratio - 8.0).abs() < 0.01,
            "1/r^3 decay: ratio = {}, expected 8.0",
            ratio
        );
    }

    #[test]
    fn test_dipole_field_linearity_in_moment() {
        let dipole_pos = [0.0, 0.0, 0.0];
        let sensor_pos = [0.0, 0.1, 0.0];
        let orient = [1.0, 0.0, 0.0];

        let b1 =
            MegProcessor::magnetic_dipole_field(dipole_pos, [1e-9, 0.0, 0.0], sensor_pos, orient);
        let b2 =
            MegProcessor::magnetic_dipole_field(dipole_pos, [2e-9, 0.0, 0.0], sensor_pos, orient);

        assert!(
            (b2 / b1 - 2.0).abs() < 1e-10,
            "Field should be linear in dipole moment"
        );
    }

    #[test]
    fn test_dipole_field_zero_at_zero_distance() {
        let b = MegProcessor::magnetic_dipole_field(
            [0.0, 0.0, 0.0],
            [1e-9, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
        );
        assert!(b.abs() < 1e-30, "Field should be zero at dipole location");
    }

    #[test]
    fn test_dipole_field_symmetry() {
        let moment = [0.0, 0.0, 1e-9]; // z-oriented dipole
        let orient = [0.0, 0.0, 1.0];

        // Field at symmetric points along x-axis
        let b_pos = MegProcessor::magnetic_dipole_field(
            [0.0, 0.0, 0.0],
            moment,
            [0.1, 0.0, 0.0],
            orient,
        );
        let b_neg = MegProcessor::magnetic_dipole_field(
            [0.0, 0.0, 0.0],
            moment,
            [-0.1, 0.0, 0.0],
            orient,
        );

        assert!(
            (b_pos - b_neg).abs() < 1e-20,
            "Field should be symmetric for symmetric sensor positions"
        );
    }

    #[test]
    fn test_dipole_field_perpendicular_moment_and_displacement() {
        // Dipole moment along x, sensor on y-axis, sensor oriented along x
        // This should give a nonzero field due to the 3(Q.r_hat)(r_hat.n) - (Q.n) term
        let b = MegProcessor::magnetic_dipole_field(
            [0.0, 0.0, 0.0],
            [1e-9, 0.0, 0.0],
            [0.0, 0.1, 0.0],
            [1.0, 0.0, 0.0],
        );
        // Q.r_hat = 0 (perpendicular), Q.n = 1e-9
        // So B = prefactor * (0 - 1e-9) = -prefactor * 1e-9
        assert!(b < 0.0, "Field should be negative in this geometry");
    }

    // =====================================================
    // Forward model tests
    // =====================================================

    #[test]
    fn test_forward_model_consistency() {
        let (positions, orientations) = test_sensor_array(16, 0.12);
        let source = DipoleSource {
            position: [0.0, 0.0, 0.0],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };

        let predicted = MegProcessor::forward_model(&source, &positions, &orientations);
        assert_eq!(predicted.len(), 16);

        // Verify each element matches direct computation
        for i in 0..16 {
            let direct = MegProcessor::magnetic_dipole_field(
                source.position,
                source.moment,
                positions[i],
                orientations[i],
            );
            let diff = (predicted[i] - direct).abs();
            let scale = predicted[i].abs().max(1e-30);
            assert!(
                diff < scale * 1e-10,
                "Forward model inconsistent at sensor {}: diff={:.2e}",
                i,
                diff
            );
        }
    }

    #[test]
    fn test_forward_model_superposition() {
        let (positions, orientations) = test_sensor_array(8, 0.12);

        let s1 = DipoleSource {
            position: [0.0, 0.0, 0.0],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };
        let s2 = DipoleSource {
            position: [0.0, 0.0, 0.0],
            moment: [0.0, 1e-9, 0.0],
            goodness_of_fit: 1.0,
        };
        let s_combined = DipoleSource {
            position: [0.0, 0.0, 0.0],
            moment: [1e-9, 1e-9, 0.0],
            goodness_of_fit: 1.0,
        };

        let f1 = MegProcessor::forward_model(&s1, &positions, &orientations);
        let f2 = MegProcessor::forward_model(&s2, &positions, &orientations);
        let fc = MegProcessor::forward_model(&s_combined, &positions, &orientations);

        for i in 0..8 {
            let diff = (fc[i] - (f1[i] + f2[i])).abs();
            let scale = fc[i].abs().max(1e-30);
            assert!(
                diff < scale * 1e-10,
                "Forward model should be linear (superposition): diff={:.2e}, scale={:.2e}",
                diff,
                scale
            );
        }
    }

    // =====================================================
    // Dipole fit tests
    // =====================================================

    #[test]
    fn test_dipole_fit_recovery() {
        let (positions, orientations) = test_sensor_array(32, 0.12);

        // Create a known source
        let true_source = DipoleSource {
            position: [0.02, 0.01, 0.0],
            moment: [1e-9, 0.5e-9, 0.0],
            goodness_of_fit: 1.0,
        };

        // Generate measurements
        let measurements =
            MegProcessor::forward_model(&true_source, &positions, &orientations);

        // Create a grid that includes the true position
        let mut grid = Vec::new();
        for ix in -3..=3 {
            for iy in -3..=3 {
                grid.push([ix as f64 * 0.01, iy as f64 * 0.01, 0.0]);
            }
        }

        let fitted = MegProcessor::dipole_fit(&measurements, &positions, &orientations, &grid);

        // GOF should be high (close to 1)
        assert!(
            fitted.goodness_of_fit > 0.95,
            "GOF = {} should be > 0.95",
            fitted.goodness_of_fit
        );

        // Position should match the nearest grid point to [0.02, 0.01, 0.0]
        let error_mm = SourceLocalizer::equivalent_current_dipole_error(
            true_source.position,
            fitted.position,
        );
        // Grid spacing is 10mm, so error should be within grid spacing
        assert!(
            error_mm < 15.0,
            "Localization error = {:.1} mm, expected < 15 mm",
            error_mm
        );
    }

    #[test]
    fn test_dipole_fit_exact_grid_point() {
        let (positions, orientations) = test_sensor_array(32, 0.12);

        let true_source = DipoleSource {
            position: [0.02, 0.02, 0.0],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };

        let measurements =
            MegProcessor::forward_model(&true_source, &positions, &orientations);

        // Grid includes exact position
        let grid = vec![
            [0.0, 0.0, 0.0],
            [0.01, 0.01, 0.0],
            [0.02, 0.02, 0.0], // Exact match
            [0.03, 0.03, 0.0],
        ];

        let fitted = MegProcessor::dipole_fit(&measurements, &positions, &orientations, &grid);

        assert!(
            fitted.goodness_of_fit > 0.999,
            "GOF = {} should be ~1.0 for exact grid match",
            fitted.goodness_of_fit
        );
        assert!(
            (fitted.position[0] - 0.02).abs() < 1e-10,
            "Should find exact grid point"
        );
        assert!(
            (fitted.position[1] - 0.02).abs() < 1e-10,
            "Should find exact grid point"
        );
    }

    // =====================================================
    // Minimum norm estimate tests
    // =====================================================

    #[test]
    fn test_minimum_norm_basic() {
        // Simple 2-sensor, 3-source problem
        let lead_field = vec![
            vec![1.0, 0.0],   // Source 0 contributes to sensor 0
            vec![0.0, 1.0],   // Source 1 contributes to sensor 1
            vec![0.5, 0.5],   // Source 2 contributes equally
        ];

        let measurements = vec![1.0, 1.0];
        let result = MegProcessor::minimum_norm_estimate(&measurements, &lead_field, 0.01);

        assert_eq!(result.len(), 3);
        // All source amplitudes should be reasonable
        for &v in &result {
            assert!(v.is_finite(), "MNE result should be finite");
        }
    }

    #[test]
    fn test_minimum_norm_regularization() {
        let lead_field = vec![vec![1.0, 0.0], vec![0.0, 1.0]];
        let measurements = vec![1.0, 1.0];

        // Larger lambda = more regularization = smaller norm
        let result_low = MegProcessor::minimum_norm_estimate(&measurements, &lead_field, 0.001);
        let result_high = MegProcessor::minimum_norm_estimate(&measurements, &lead_field, 10.0);

        let norm_low: f64 = result_low.iter().map(|x| x * x).sum();
        let norm_high: f64 = result_high.iter().map(|x| x * x).sum();

        assert!(
            norm_low > norm_high,
            "Higher regularization should produce smaller norm estimate"
        );
    }

    #[test]
    fn test_minimum_norm_empty_input() {
        let result = MegProcessor::minimum_norm_estimate(&[], &[], 0.01);
        assert!(result.is_empty());
    }

    // =====================================================
    // Beamformer tests
    // =====================================================

    #[test]
    fn test_beamformer_lcmv_peaks_at_source() {
        let (positions, orientations) = test_sensor_array(16, 0.12);
        let n_sensors = 16;
        let n_samples = 500;

        // Generate data from a single dipole source
        let source = DipoleSource {
            position: [0.02, 0.0, 0.0],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };

        let field = MegProcessor::forward_model(&source, &positions, &orientations);

        // Create time-series data: source signal + per-channel independent noise
        // The noise ensures the covariance matrix is full rank
        let mut data = vec![vec![0.0f64; n_samples]; n_sensors];
        let mut seed: u64 = 42;
        for ch in 0..n_sensors {
            for s in 0..n_samples {
                let t = s as f64 / 1000.0;
                // LCG pseudo-random noise
                seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                let noise = ((seed >> 33) as f64 / (1u64 << 31) as f64 - 0.5) * field[ch].abs() * 0.3;
                data[ch][s] = field[ch] * (2.0 * PI * 10.0 * t).sin() + noise;
            }
        }

        // Compute lead fields at source location and at a wrong location
        let lf_source: Vec<f64> = positions
            .iter()
            .zip(orientations.iter())
            .map(|(sp, so)| {
                MegProcessor::magnetic_dipole_field([0.02, 0.0, 0.0], [1.0, 0.0, 0.0], *sp, *so)
            })
            .collect();

        let lf_wrong: Vec<f64> = positions
            .iter()
            .zip(orientations.iter())
            .map(|(sp, so)| {
                MegProcessor::magnetic_dipole_field([-0.05, -0.05, 0.0], [1.0, 0.0, 0.0], *sp, *so)
            })
            .collect();

        let power_source = MegProcessor::beamformer_lcmv(&data, &lf_source);
        let power_wrong = MegProcessor::beamformer_lcmv(&data, &lf_wrong);

        // Both should be non-zero and source should have more power
        assert!(
            power_source.abs() > 1e-30 && power_wrong.abs() > 1e-30,
            "Both powers should be non-zero: source={:.2e}, wrong={:.2e}",
            power_source,
            power_wrong
        );
        assert!(
            power_source > power_wrong,
            "Beamformer should have more power at source ({:.2e}) than away ({:.2e})",
            power_source,
            power_wrong
        );
    }

    // =====================================================
    // Preprocessing tests
    // =====================================================

    #[test]
    fn test_bandpass_passes_target_frequency() {
        let sample_rate = 1000.0;
        let target_freq = 20.0;
        let n_samples = 2000;

        // Create signal with target freq + out-of-band components
        let mut signal = Vec::with_capacity(n_samples);
        for i in 0..n_samples {
            let t = i as f64 / sample_rate;
            signal.push(
                (2.0 * PI * target_freq * t).sin()   // In-band
                + (2.0 * PI * 200.0 * t).sin()         // Out-of-band high
                + 0.5,                                  // DC offset
            );
        }

        let filtered = SignalPreprocessor::bandpass(&signal, 10.0, 30.0, sample_rate);

        // Measure power in latter half (after filter settling)
        let n_start = n_samples / 2;
        let power: f64 = filtered[n_start..]
            .iter()
            .map(|x| x * x)
            .sum::<f64>()
            / (n_samples - n_start) as f64;

        // Should have significant power (target freq passes through)
        assert!(
            power > 0.1,
            "Bandpass should pass target frequency, power = {}",
            power
        );
    }

    #[test]
    fn test_notch_filter_removes_frequency() {
        let sample_rate = 1000.0;
        let notch_freq = 50.0;
        let n_samples = 2000;

        let mut signal = Vec::with_capacity(n_samples);
        for i in 0..n_samples {
            let t = i as f64 / sample_rate;
            signal.push(
                (2.0 * PI * notch_freq * t).sin() + (2.0 * PI * 20.0 * t).sin(),
            );
        }

        // Measure 50 Hz power before
        let power_before = goertzel_power(&signal, notch_freq, sample_rate);

        let mut filtered = signal.clone();
        SignalPreprocessor::notch_filter(&mut filtered, notch_freq, sample_rate, 30.0);

        let power_after = goertzel_power(&filtered[500..], notch_freq, sample_rate);

        assert!(
            power_after < power_before * 0.01,
            "Notch should reduce 50 Hz power by >20 dB"
        );
    }

    #[test]
    fn test_ssp_projection_removes_artifact() {
        let n_channels = 4;
        let n_samples = 100;

        // Create data: signal + artifact
        let mut data = vec![vec![0.0f64; n_samples]; n_channels];
        let artifact_pattern = vec![1.0, 0.5, 0.3, 0.1]; // Spatial pattern of artifact

        for s in 0..n_samples {
            let artifact = (s as f64 * 0.1).sin(); // Time course of artifact
            let signal = (s as f64 * 0.5).cos() * 0.1; // Weak signal
            for ch in 0..n_channels {
                data[ch][s] = artifact * artifact_pattern[ch] + signal;
            }
        }

        // Project out the artifact pattern
        let projectors = vec![artifact_pattern.clone()];
        SignalPreprocessor::ssp_projection(&mut data, &projectors);

        // The projection of data onto artifact pattern should be near zero
        for s in 0..n_samples {
            let mut projection = 0.0;
            let mut norm = 0.0;
            for ch in 0..n_channels {
                projection += data[ch][s] * artifact_pattern[ch];
                norm += artifact_pattern[ch] * artifact_pattern[ch];
            }
            projection /= norm;
            assert!(
                projection.abs() < 1e-10,
                "SSP should remove artifact component, got {}",
                projection
            );
        }
    }

    #[test]
    fn test_covariance_matrix_symmetric() {
        let data = vec![
            vec![1.0, 2.0, 3.0, 4.0],
            vec![2.0, 3.0, 1.0, 5.0],
            vec![0.5, 1.5, 2.5, 3.5],
        ];

        let cov = SignalPreprocessor::covariance_matrix(&data);

        assert_eq!(cov.len(), 3);
        assert_eq!(cov[0].len(), 3);

        // Check symmetry
        for i in 0..3 {
            for j in 0..3 {
                assert!(
                    (cov[i][j] - cov[j][i]).abs() < 1e-15,
                    "Covariance matrix should be symmetric"
                );
            }
        }
    }

    #[test]
    fn test_covariance_matrix_positive_diagonal() {
        let data = vec![
            vec![1.0, -1.0, 2.0, -2.0],
            vec![3.0, 1.0, -1.0, 0.0],
        ];

        let cov = SignalPreprocessor::covariance_matrix(&data);

        for i in 0..2 {
            assert!(
                cov[i][i] >= 0.0,
                "Diagonal elements should be non-negative (variance)"
            );
        }
    }

    #[test]
    fn test_whitening_matrix_decorrelates() {
        // Create correlated data
        let data = vec![
            vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0],
            vec![1.1, 2.2, 2.9, 4.1, 5.0, 6.1, 6.9, 8.1],
        ];

        let cov = SignalPreprocessor::covariance_matrix(&data);
        let w = SignalPreprocessor::whitening_matrix(&cov);

        assert_eq!(w.len(), 2);
        assert_eq!(w[0].len(), 2);

        // Apply whitening: new_cov should be approximately identity
        // W * C * W^T should be ~ I
        let mut wcwt = vec![vec![0.0f64; 2]; 2];
        for i in 0..2 {
            for j in 0..2 {
                for k in 0..2 {
                    for l in 0..2 {
                        wcwt[i][j] += w[i][k] * cov[k][l] * w[j][l];
                    }
                }
            }
        }

        // Check approximately identity
        for i in 0..2 {
            for j in 0..2 {
                let expected = if i == j { 1.0 } else { 0.0 };
                assert!(
                    (wcwt[i][j] - expected).abs() < 0.1,
                    "Whitened covariance should be ~identity, got [{},{}] = {}",
                    i,
                    j,
                    wcwt[i][j]
                );
            }
        }
    }

    // =====================================================
    // Source localization tests
    // =====================================================

    #[test]
    fn test_dipole_scanning_finds_source() {
        let (positions, orientations) = test_sensor_array(24, 0.12);

        let true_source = DipoleSource {
            position: [0.03, 0.0, 0.0],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };

        let measurements =
            MegProcessor::forward_model(&true_source, &positions, &orientations);

        let mut grid = Vec::new();
        for ix in -5..=5 {
            for iy in -5..=5 {
                grid.push([ix as f64 * 0.01, iy as f64 * 0.01, 0.0]);
            }
        }

        let results =
            SourceLocalizer::dipole_scanning(&measurements, &grid, &positions, &orientations);

        // Best result should be at or near the true source
        let (best_gof, best_pos) = results[0];
        assert!(best_gof > 0.9, "Best GOF = {}, should be > 0.9", best_gof);

        let error =
            SourceLocalizer::equivalent_current_dipole_error(true_source.position, best_pos);
        assert!(
            error < 15.0,
            "Best position error = {:.1} mm, should be < 15 mm (grid spacing = 10 mm)",
            error
        );
    }

    #[test]
    fn test_dipole_scanning_sorted_by_gof() {
        let (positions, orientations) = test_sensor_array(16, 0.12);

        let source = DipoleSource {
            position: [0.02, 0.0, 0.0],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };

        let measurements =
            MegProcessor::forward_model(&source, &positions, &orientations);

        let grid = vec![[0.0, 0.0, 0.0], [0.02, 0.0, 0.0], [0.05, 0.05, 0.0]];

        let results =
            SourceLocalizer::dipole_scanning(&measurements, &grid, &positions, &orientations);

        // Should be sorted descending by GOF
        for i in 1..results.len() {
            assert!(
                results[i - 1].0 >= results[i].0,
                "Results should be sorted by descending GOF"
            );
        }
    }

    #[test]
    fn test_localization_error_computation() {
        let true_pos = [0.01, 0.02, 0.03];
        let est_pos = [0.011, 0.021, 0.031];

        let error = SourceLocalizer::equivalent_current_dipole_error(true_pos, est_pos);

        // sqrt(0.001^2 + 0.001^2 + 0.001^2) * 1000 = sqrt(3) * 1 mm ~ 1.73 mm
        let expected = (3.0f64).sqrt();
        assert!(
            (error - expected).abs() < 0.01,
            "Error = {:.2} mm, expected {:.2} mm",
            error,
            expected
        );
    }

    #[test]
    fn test_localization_error_zero_for_same_position() {
        let pos = [0.05, -0.03, 0.07];
        let error = SourceLocalizer::equivalent_current_dipole_error(pos, pos);
        assert!(error.abs() < 1e-10);
    }

    #[test]
    fn test_music_localization_basic() {
        let n_channels = 8;
        let n_samples = 200;
        let (positions, orientations) = test_sensor_array(n_channels, 0.12);

        // Create data from a single source
        let source = DipoleSource {
            position: [0.03, 0.0, 0.0],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };

        let field = MegProcessor::forward_model(&source, &positions, &orientations);

        let mut data = vec![vec![0.0f64; n_samples]; n_channels];
        for ch in 0..n_channels {
            for s in 0..n_samples {
                let t = s as f64 / 1000.0;
                data[ch][s] =
                    field[ch] * (2.0 * PI * 10.0 * t).sin() + 1e-16 * ((s * ch) as f64 * 0.01);
            }
        }

        let cov = SignalPreprocessor::covariance_matrix(&data);

        // Create lead fields at two grid points
        let grid_points: Vec<[f64; 3]> = vec![[0.03, 0.0, 0.0], [-0.03, 0.0, 0.0]];

        let lead_fields: Vec<Vec<Vec<f64>>> = grid_points
            .iter()
            .map(|gp| {
                let lf: Vec<f64> = positions
                    .iter()
                    .zip(orientations.iter())
                    .map(|(sp, so)| {
                        MegProcessor::magnetic_dipole_field(*gp, [1.0, 0.0, 0.0], *sp, *so)
                    })
                    .collect();
                vec![lf]
            })
            .collect();

        let spectrum = SourceLocalizer::music_localization(&cov, &lead_fields, 1);

        assert_eq!(spectrum.len(), 2);
        // MUSIC pseudo-spectrum should be higher at the source location
        assert!(
            spectrum[0] > spectrum[1],
            "MUSIC should peak at source: {:.2e} vs {:.2e}",
            spectrum[0],
            spectrum[1]
        );
    }

    // =====================================================
    // Connectivity tests
    // =====================================================

    #[test]
    fn test_coherence_identical_signals() {
        let sample_rate = 1000.0;
        let fft_size = 64;
        let n = 512; // Multiple segments for Welch averaging
        let signal: Vec<f64> = (0..n)
            .map(|i| (2.0 * PI * 40.0 * i as f64 / sample_rate).sin())
            .collect();

        let coh = ConnectivityAnalyzer::coherence(&signal, &signal, sample_rate, fft_size);

        // Find coherence near 40 Hz
        let target_bin = (40.0 / (sample_rate / fft_size as f64)).round() as usize;
        if target_bin < coh.len() {
            assert!(
                coh[target_bin].1 > 0.99,
                "Coherence of identical signals should be ~1.0 at signal frequency, got {}",
                coh[target_bin].1
            );
        }
    }

    #[test]
    fn test_coherence_uncorrelated_signals() {
        let sample_rate = 1000.0;
        let fft_size = 64;
        let n = 1024; // Long signals for proper Welch averaging

        // Two independent pseudo-random signals
        let sig1: Vec<f64> = (0..n)
            .map(|i| {
                ((i as f64 * 7.31 + 2.17).sin() * 43758.5453).fract()
            })
            .collect();
        let sig2: Vec<f64> = (0..n)
            .map(|i| {
                ((i as f64 * 13.97 + 5.43).sin() * 23421.6312).fract()
            })
            .collect();

        let coh = ConnectivityAnalyzer::coherence(&sig1, &sig2, sample_rate, fft_size);

        // Average coherence of uncorrelated signals should be low
        let avg_coh: f64 = coh.iter().map(|(_, c)| c).sum::<f64>() / coh.len() as f64;
        assert!(
            avg_coh < 0.8,
            "Average coherence of uncorrelated signals should be low, got {}",
            avg_coh
        );
    }

    #[test]
    fn test_imaginary_coherence_zero_lag() {
        let sample_rate = 1000.0;
        let fft_size = 64;
        let n = 512;

        // Identical signals should have zero imaginary coherence (purely real cross-spectrum)
        let signal: Vec<f64> = (0..n)
            .map(|i| (2.0 * PI * 40.0 * i as f64 / sample_rate).sin())
            .collect();

        let icoh =
            ConnectivityAnalyzer::imaginary_coherence(&signal, &signal, sample_rate, fft_size);

        // Average imaginary coherence should be near zero for identical signals
        let avg_icoh: f64 = icoh.iter().map(|(_, c)| c).sum::<f64>() / icoh.len().max(1) as f64;
        assert!(
            avg_icoh < 0.05,
            "Imaginary coherence of identical signals should be ~0, got {}",
            avg_icoh
        );
    }

    #[test]
    fn test_imaginary_coherence_phase_shifted() {
        let sample_rate = 1000.0;
        let fft_size = 64;
        let n = 512;

        // Two signals with a phase shift (non-zero imaginary coherence)
        let sig1: Vec<f64> = (0..n)
            .map(|i| (2.0 * PI * 40.0 * i as f64 / sample_rate).sin())
            .collect();
        let sig2: Vec<f64> = (0..n)
            .map(|i| (2.0 * PI * 40.0 * i as f64 / sample_rate + PI / 4.0).sin())
            .collect();

        let icoh =
            ConnectivityAnalyzer::imaginary_coherence(&sig1, &sig2, sample_rate, fft_size);

        // Should have non-zero imaginary coherence at the signal frequency
        let target_bin = (40.0 / (sample_rate / fft_size as f64)).round() as usize;
        if target_bin < icoh.len() {
            assert!(
                icoh[target_bin].1 > 0.1,
                "Phase-shifted signals should have non-zero imaginary coherence, got {}",
                icoh[target_bin].1
            );
        }
    }

    #[test]
    fn test_phase_transfer_entropy_non_negative() {
        let n = 500;
        let x: Vec<f64> = (0..n).map(|i| (i as f64 * 0.1).sin()).collect();
        let y: Vec<f64> = (0..n).map(|i| (i as f64 * 0.2).cos()).collect();

        let te = ConnectivityAnalyzer::phase_transfer_entropy(&x, &y, 1);
        assert!(
            te >= 0.0,
            "Transfer entropy should be non-negative, got {}",
            te
        );
    }

    #[test]
    fn test_phase_transfer_entropy_directed() {
        // Create a coupled autoregressive system where x -> y
        let n = 5000;
        let lag = 1;

        // Generate x using LCG
        let mut x = vec![0.0f64; n];
        let mut seed: u64 = 12345;
        for i in 0..n {
            seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            x[i] = (seed >> 33) as f64 / (1u64 << 31) as f64;
        }

        // y[t] = x[t-1] deterministically (perfect copy with lag)
        let mut y = vec![0.0f64; n];
        for i in lag..n {
            y[i] = x[i - lag];
        }

        // For identical signals with lag, TE(x->y) should be positive
        // and TE(y->x) at the same lag should be smaller since y doesn't drive x
        let te_x_to_y = ConnectivityAnalyzer::phase_transfer_entropy(&x, &y, lag);
        let te_y_to_x = ConnectivityAnalyzer::phase_transfer_entropy(&y, &x, lag);

        // Both should be non-negative
        assert!(te_x_to_y >= 0.0);
        assert!(te_y_to_x >= 0.0);

        // With a deterministic copy, TE in the causal direction should be detectable
        // At minimum, TE(x->y) should be meaningfully positive
        assert!(
            te_x_to_y > 0.001,
            "TE(x->y) = {:.4} should be meaningfully positive for deterministic coupling",
            te_x_to_y,
        );
    }

    #[test]
    fn test_phase_transfer_entropy_short_signal() {
        let x = vec![1.0, 2.0];
        let y = vec![3.0, 4.0];
        let te = ConnectivityAnalyzer::phase_transfer_entropy(&x, &y, 5);
        assert!((te - 0.0).abs() < 1e-15, "Too-short signal should return 0");
    }

    // =====================================================
    // Edge case and helper tests
    // =====================================================

    #[test]
    fn test_solve_3x3_identity() {
        let a = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]];
        let b = [3.0, 5.0, 7.0];
        let x = solve_3x3(&a, &b);
        assert!((x[0] - 3.0).abs() < 1e-10);
        assert!((x[1] - 5.0).abs() < 1e-10);
        assert!((x[2] - 7.0).abs() < 1e-10);
    }

    #[test]
    fn test_solve_3x3_singular() {
        let a = [[1.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 1.0]];
        let b = [1.0, 1.0, 1.0];
        let x = solve_3x3(&a, &b);
        // Should return zeros for singular matrix
        assert!((x[0]).abs() < 1e-10);
        assert!((x[1]).abs() < 1e-10);
        assert!((x[2]).abs() < 1e-10);
    }

    #[test]
    fn test_bandpass_empty_signal() {
        let result = SignalPreprocessor::bandpass(&[], 10.0, 100.0, 1000.0);
        assert!(result.is_empty());
    }

    #[test]
    fn test_forward_model_empty() {
        let source = DipoleSource {
            position: [0.0; 3],
            moment: [1e-9, 0.0, 0.0],
            goodness_of_fit: 1.0,
        };
        let result = MegProcessor::forward_model(&source, &[], &[]);
        assert!(result.is_empty());
    }

    #[test]
    fn test_dipole_moment_estimation_accuracy() {
        let (positions, orientations) = test_sensor_array(32, 0.12);

        let true_moment = [1e-9, 2e-9, 0.5e-9];
        let true_source = DipoleSource {
            position: [0.02, 0.0, 0.0],
            moment: true_moment,
            goodness_of_fit: 1.0,
        };

        let measurements =
            MegProcessor::forward_model(&true_source, &positions, &orientations);

        // Grid includes exact position
        let grid = vec![[0.02, 0.0, 0.0]];

        let fitted = MegProcessor::dipole_fit(&measurements, &positions, &orientations, &grid);

        // Moment should match closely
        for i in 0..3 {
            let relative_error = if true_moment[i].abs() > 1e-15 {
                (fitted.moment[i] - true_moment[i]).abs() / true_moment[i].abs()
            } else {
                fitted.moment[i].abs()
            };
            assert!(
                relative_error < 0.01,
                "Moment[{}] relative error = {:.4}, expected < 0.01",
                i,
                relative_error
            );
        }
    }

    /// Helper: compute Goertzel power at a specific frequency.
    fn goertzel_power(signal: &[f64], freq_hz: f64, sample_rate: f64) -> f64 {
        let n = signal.len();
        let k = (freq_hz * n as f64 / sample_rate).round();
        let w = 2.0 * PI * k / n as f64;
        let coeff = 2.0 * w.cos();

        let mut s0 = 0.0;
        let mut s1 = 0.0;
        let mut s2 = 0.0;

        for &x in signal {
            s0 = x + coeff * s1 - s2;
            s2 = s1;
            s1 = s0;
        }

        let real = s1 - s2 * w.cos();
        let imag = s2 * w.sin();
        (real * real + imag * imag) / (n as f64 * n as f64)
    }
}
