//! Volcanic Seismic Signal Analysis for Eruption Monitoring
//!
//! This module implements volcanic seismology algorithms for real-time eruption
//! monitoring and precursor detection. It covers harmonic tremor detection,
//! Real-time Seismic Amplitude Measurement (RSAM), frequency gliding analysis,
//! and volcanic event classification.
//!
//! ## Background
//!
//! Volcanic tremor is a continuous seismic signal generated by fluid movement
//! within volcanic conduits. Its characteristics (frequency content, amplitude,
//! spectral evolution) provide critical indicators of volcanic unrest:
//!
//! - **RSAM** (Real-time Seismic Amplitude Measurement): Time-averaged absolute
//!   amplitude that tracks overall volcanic energy release. Sustained RSAM
//!   increases often precede eruptions.
//! - **Harmonic tremor**: Quasi-sinusoidal signals with fundamental frequency
//!   and overtones, generated by resonance of magma-filled conduits.
//! - **Frequency gliding**: Progressive shift of tremor spectral peaks over
//!   hours to days, indicating changes in conduit geometry or gas content.
//! - **Event classification**: Distinguishing volcano-tectonic (VT), long-period
//!   (LP), hybrid, and tremor events based on spectral and temporal features.
//!
//! ## References
//!
//! - Endo & Murray (1991): RSAM methodology, USGS
//! - Chouet (1996): Long-period volcano seismicity
//! - McNutt (2005): Volcanic seismology review
//! - Lahr et al. (1994): Reduced displacement calculation
//!
//! ## Example
//!
//! ```rust
//! use r4w_core::volcanic_tremor_analyzer::{
//!     TremorConfig, RsamCalculator, HarmonicTremorDetector,
//!     dominant_frequency, spectral_ratio,
//! };
//!
//! let config = TremorConfig::default();
//!
//! // Compute RSAM on a seismic trace
//! let mut rsam = RsamCalculator::new(config.clone());
//! let trace: Vec<f64> = (0..6000)
//!     .map(|i| {
//!         let t = i as f64 / config.sample_rate;
//!         (2.0 * std::f64::consts::PI * 2.0 * t).sin() * 100.0
//!     })
//!     .collect();
//! let rsam_values = rsam.process(&trace);
//! assert!(!rsam_values.is_empty());
//!
//! // Detect harmonic tremor
//! let mut detector = HarmonicTremorDetector::new(config.clone());
//! let result = detector.analyze(&trace);
//! assert!(result.fundamental_freq > 0.0);
//!
//! // Helper functions
//! let freq = dominant_frequency(&trace, config.sample_rate);
//! assert!(freq > 0.0);
//!
//! let ratio = spectral_ratio(&trace, config.sample_rate, 1.0, 5.0, 5.0, 15.0);
//! assert!(ratio >= 0.0);
//! ```

use std::f64::consts::PI;

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/// Configuration for volcanic tremor analysis.
#[derive(Debug, Clone)]
pub struct TremorConfig {
    /// Seismometer sample rate in Hz. Typical broadband: 100 Hz.
    pub sample_rate: f64,

    /// Low-frequency band lower bound (Hz) for LP event detection.
    pub lp_band_low: f64,

    /// Low-frequency band upper bound (Hz) for LP event detection.
    pub lp_band_high: f64,

    /// High-frequency band lower bound (Hz) for VT event detection.
    pub vt_band_low: f64,

    /// High-frequency band upper bound (Hz) for VT event detection.
    pub vt_band_high: f64,

    /// RSAM window duration in seconds (typically 600 s = 10 minutes).
    pub rsam_window_secs: f64,

    /// FFT size for spectral analysis (power of 2).
    pub fft_size: usize,

    /// Minimum number of harmonics to declare harmonic tremor.
    pub min_harmonics: usize,

    /// Harmonic frequency tolerance as a fraction of the fundamental
    /// (e.g., 0.05 means 5% tolerance).
    pub harmonic_tolerance: f64,
}

impl Default for TremorConfig {
    fn default() -> Self {
        Self {
            sample_rate: 100.0,
            lp_band_low: 0.5,
            lp_band_high: 5.0,
            vt_band_low: 5.0,
            vt_band_high: 15.0,
            rsam_window_secs: 600.0,
            fft_size: 1024,
            min_harmonics: 3,
            harmonic_tolerance: 0.05,
        }
    }
}

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

/// Classification of volcanic seismic events.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VolcanicEventType {
    /// Volcano-Tectonic: brittle failure, high-frequency (>5 Hz), clear P/S.
    VT,
    /// Long-Period: fluid-driven, low-frequency (0.5-5 Hz), emergent onset.
    LP,
    /// Hybrid: combination of VT onset and LP coda.
    Hybrid,
    /// Volcanic tremor: continuous, often harmonic, fluid-resonance.
    Tremor,
    /// Unknown or unclassifiable event.
    Unknown,
}

/// Result from harmonic tremor detection.
#[derive(Debug, Clone)]
pub struct HarmonicTremorResult {
    /// Detected fundamental frequency in Hz (0 if no harmonic structure found).
    pub fundamental_freq: f64,

    /// Frequencies of detected harmonic peaks (Hz).
    pub harmonic_freqs: Vec<f64>,

    /// Amplitudes of detected harmonic peaks (same units as input).
    pub harmonic_amplitudes: Vec<f64>,

    /// Whether the signal contains harmonic tremor.
    pub is_harmonic: bool,

    /// Quality factor (sharpness of spectral peaks).
    pub quality_factor: f64,
}

/// Result from frequency gliding tracking.
#[derive(Debug, Clone)]
pub struct GlidingResult {
    /// Time stamps of each measurement window (seconds from start).
    pub times: Vec<f64>,

    /// Dominant frequency at each time step (Hz).
    pub frequencies: Vec<f64>,

    /// Gliding rate in Hz/hour (positive = upward glide).
    pub gliding_rate_hz_per_hour: f64,

    /// Whether frequency gliding is detected.
    pub is_gliding: bool,
}

/// Eruption precursor assessment.
#[derive(Debug, Clone)]
pub struct PrecursorResult {
    /// Current RSAM level relative to baseline (ratio).
    pub rsam_ratio: f64,

    /// RSAM trend (positive = increasing). Units: counts/hour.
    pub rsam_trend: f64,

    /// Low-to-high frequency spectral ratio.
    pub spectral_ratio: f64,

    /// Alert level: 0 = background, 1 = elevated, 2 = high, 3 = critical.
    pub alert_level: u8,

    /// Summary description of the assessment.
    pub summary: String,
}

/// Result from volcanic event classification.
#[derive(Debug, Clone)]
pub struct ClassificationResult {
    /// Classified event type.
    pub event_type: VolcanicEventType,

    /// Confidence in the classification (0.0 - 1.0).
    pub confidence: f64,

    /// Dominant frequency of the event (Hz).
    pub dominant_freq: f64,

    /// Duration of the event (seconds).
    pub duration_secs: f64,

    /// Peak amplitude (same units as input).
    pub peak_amplitude: f64,
}

// ---------------------------------------------------------------------------
// Internal FFT helpers (radix-2 DIT, no external crate)
// ---------------------------------------------------------------------------

/// Compute the next power of two >= n.
fn next_pow2(n: usize) -> usize {
    let mut p = 1;
    while p < n {
        p <<= 1;
    }
    p
}

/// Radix-2 decimation-in-time FFT (in-place).
/// `real` and `imag` are modified in-place and must have length = power of 2.
fn fft_inplace(real: &mut [f64], imag: &mut [f64]) {
    let n = real.len();
    debug_assert!(n.is_power_of_two());
    debug_assert_eq!(n, imag.len());

    // Bit-reversal permutation
    let mut j = 0usize;
    for i in 0..n {
        if i < j {
            real.swap(i, j);
            imag.swap(i, j);
        }
        let mut m = n >> 1;
        while m >= 1 && j >= m {
            j -= m;
            m >>= 1;
        }
        j += m;
    }

    // Cooley-Tukey butterfly
    let mut size = 2;
    while size <= n {
        let half = size / 2;
        let angle_step = -2.0 * PI / size as f64;
        for k in 0..half {
            let angle = angle_step * k as f64;
            let wr = angle.cos();
            let wi = angle.sin();
            let mut idx = k;
            while idx < n {
                let partner = idx + half;
                let tr = wr * real[partner] - wi * imag[partner];
                let ti = wr * imag[partner] + wi * real[partner];
                real[partner] = real[idx] - tr;
                imag[partner] = imag[idx] - ti;
                real[idx] += tr;
                imag[idx] += ti;
                idx += size;
            }
        }
        size <<= 1;
    }
}

/// Compute the magnitude spectrum (one-sided) of a real signal.
/// Returns (frequencies_hz, magnitudes). Length = fft_size/2 + 1.
fn magnitude_spectrum(signal: &[f64], fft_size: usize, sample_rate: f64) -> (Vec<f64>, Vec<f64>) {
    let n = next_pow2(fft_size);
    let mut real = vec![0.0; n];
    let mut imag = vec![0.0; n];

    // Apply Hann window and copy
    let len = signal.len().min(n);
    for i in 0..len {
        let w = 0.5 * (1.0 - (2.0 * PI * i as f64 / len as f64).cos());
        real[i] = signal[i] * w;
    }

    fft_inplace(&mut real, &mut imag);

    let num_bins = n / 2 + 1;
    let mut freqs = Vec::with_capacity(num_bins);
    let mut mags = Vec::with_capacity(num_bins);
    let freq_res = sample_rate / n as f64;
    for i in 0..num_bins {
        freqs.push(i as f64 * freq_res);
        mags.push((real[i] * real[i] + imag[i] * imag[i]).sqrt());
    }
    (freqs, mags)
}

// ---------------------------------------------------------------------------
// RsamCalculator
// ---------------------------------------------------------------------------

/// Real-time Seismic Amplitude Measurement (RSAM) calculator.
///
/// RSAM computes the mean absolute amplitude of the seismic signal over
/// fixed-length windows (typically 10 minutes). It is the primary metric
/// for tracking volcanic energy release in real time.
///
/// Developed by Endo & Murray (1991) at USGS for monitoring Mount Pinatubo.
#[derive(Debug, Clone)]
pub struct RsamCalculator {
    config: TremorConfig,
    /// Number of samples per RSAM window.
    window_samples: usize,
    /// Baseline RSAM value for normalization.
    baseline: Option<f64>,
}

impl RsamCalculator {
    /// Create a new RSAM calculator.
    pub fn new(config: TremorConfig) -> Self {
        let window_samples = (config.rsam_window_secs * config.sample_rate) as usize;
        Self {
            config,
            window_samples: window_samples.max(1),
            baseline: None,
        }
    }

    /// Set the baseline RSAM value for ratio computations.
    pub fn set_baseline(&mut self, baseline: f64) {
        self.baseline = Some(baseline);
    }

    /// Process a continuous seismic trace and return RSAM values.
    ///
    /// Each RSAM value is the mean absolute amplitude over one window.
    /// Returns one value per complete window in the input.
    pub fn process(&mut self, signal: &[f64]) -> Vec<f64> {
        if signal.is_empty() || self.window_samples == 0 {
            return Vec::new();
        }
        let num_windows = signal.len() / self.window_samples;
        let mut rsam_values = Vec::with_capacity(num_windows);
        for w in 0..num_windows {
            let start = w * self.window_samples;
            let end = start + self.window_samples;
            let sum: f64 = signal[start..end].iter().map(|x| x.abs()).sum();
            rsam_values.push(sum / self.window_samples as f64);
        }
        rsam_values
    }

    /// Compute the RSAM ratio relative to baseline.
    /// Returns None if no baseline is set.
    pub fn rsam_ratio(&self, rsam_value: f64) -> Option<f64> {
        self.baseline.map(|b| {
            if b > 0.0 {
                rsam_value / b
            } else {
                0.0
            }
        })
    }

    /// Compute RSAM trend (slope) from a sequence of RSAM values.
    ///
    /// Uses linear regression to find the slope in units of RSAM_units/window.
    /// Multiply by (3600 / rsam_window_secs) to get per-hour rate.
    pub fn compute_trend(&self, rsam_values: &[f64]) -> f64 {
        linear_slope(rsam_values)
    }

    /// Return the window size in samples.
    pub fn window_samples(&self) -> usize {
        self.window_samples
    }
}

// ---------------------------------------------------------------------------
// HarmonicTremorDetector
// ---------------------------------------------------------------------------

/// Detector for harmonic volcanic tremor.
///
/// Harmonic tremor is characterised by a series of spectral peaks at integer
/// multiples of a fundamental frequency, typically 0.5-5 Hz. The detector
/// finds spectral peaks and checks for harmonic relationships.
#[derive(Debug, Clone)]
pub struct HarmonicTremorDetector {
    config: TremorConfig,
}

impl HarmonicTremorDetector {
    /// Create a new harmonic tremor detector.
    pub fn new(config: TremorConfig) -> Self {
        Self { config }
    }

    /// Analyze a signal segment for harmonic tremor.
    pub fn analyze(&mut self, signal: &[f64]) -> HarmonicTremorResult {
        if signal.len() < 4 {
            return HarmonicTremorResult {
                fundamental_freq: 0.0,
                harmonic_freqs: Vec::new(),
                harmonic_amplitudes: Vec::new(),
                is_harmonic: false,
                quality_factor: 0.0,
            };
        }

        let fft_size = self.config.fft_size.min(signal.len());
        let (freqs, mags) = magnitude_spectrum(signal, fft_size, self.config.sample_rate);

        // Find spectral peaks above a threshold (mean + 2*std)
        let mean_mag: f64 = mags.iter().sum::<f64>() / mags.len() as f64;
        let var: f64 =
            mags.iter().map(|m| (m - mean_mag).powi(2)).sum::<f64>() / mags.len() as f64;
        let std_mag = var.sqrt();
        let threshold = mean_mag + 2.0 * std_mag;

        let mut peaks: Vec<(f64, f64)> = Vec::new(); // (freq, amplitude)
        for i in 1..mags.len() - 1 {
            if mags[i] > threshold && mags[i] > mags[i - 1] && mags[i] > mags[i + 1] {
                // Only consider frequencies in the tremor band (0.5 - 20 Hz)
                if freqs[i] >= 0.3 && freqs[i] <= 20.0 {
                    peaks.push((freqs[i], mags[i]));
                }
            }
        }

        // Sort peaks by amplitude descending
        peaks.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

        if peaks.is_empty() {
            return HarmonicTremorResult {
                fundamental_freq: 0.0,
                harmonic_freqs: Vec::new(),
                harmonic_amplitudes: Vec::new(),
                is_harmonic: false,
                quality_factor: 0.0,
            };
        }

        // Try each peak as a candidate fundamental
        let mut best_fundamental = 0.0;
        let mut best_harmonics: Vec<(f64, f64)> = Vec::new();

        for &(f0_candidate, _) in peaks.iter().take(5) {
            if f0_candidate < 0.3 {
                continue;
            }
            let mut harmonics: Vec<(f64, f64)> = Vec::new();
            harmonics.push((f0_candidate, peaks.iter().find(|p| (p.0 - f0_candidate).abs() < 1e-9).map_or(0.0, |p| p.1)));

            // Check integer multiples
            for n in 2..=8 {
                let expected = f0_candidate * n as f64;
                if expected > self.config.sample_rate / 2.0 {
                    break;
                }
                let tol = f0_candidate * self.config.harmonic_tolerance * n as f64;
                if let Some(&(freq, amp)) = peaks.iter().find(|&&(f, _)| (f - expected).abs() < tol) {
                    harmonics.push((freq, amp));
                }
            }

            if harmonics.len() > best_harmonics.len() {
                best_fundamental = f0_candidate;
                best_harmonics = harmonics;
            }
        }

        let is_harmonic = best_harmonics.len() >= self.config.min_harmonics;

        // Quality factor: ratio of peak energy to total spectral energy
        let total_energy: f64 = mags.iter().map(|m| m * m).sum();
        let peak_energy: f64 = best_harmonics.iter().map(|(_, a)| a * a).sum();
        let quality_factor = if total_energy > 0.0 {
            peak_energy / total_energy
        } else {
            0.0
        };

        HarmonicTremorResult {
            fundamental_freq: best_fundamental,
            harmonic_freqs: best_harmonics.iter().map(|(f, _)| *f).collect(),
            harmonic_amplitudes: best_harmonics.iter().map(|(_, a)| *a).collect(),
            is_harmonic,
            quality_factor,
        }
    }
}

// ---------------------------------------------------------------------------
// FrequencyGlidingTracker
// ---------------------------------------------------------------------------

/// Tracks frequency gliding — progressive spectral peak migration over time.
///
/// Frequency gliding is an important eruption precursor. The dominant tremor
/// frequency may shift upward (conduit narrowing, increasing gas pressure)
/// or downward (conduit widening, magma ascent) over hours to days.
#[derive(Debug, Clone)]
pub struct FrequencyGlidingTracker {
    config: TremorConfig,
    /// Step size in samples between successive analysis windows.
    step_samples: usize,
    /// Analysis window size in samples.
    window_samples: usize,
}

impl FrequencyGlidingTracker {
    /// Create a new frequency gliding tracker.
    ///
    /// `window_secs` is the spectral analysis window, `step_secs` is the
    /// time step between windows.
    pub fn new(config: TremorConfig, window_secs: f64, step_secs: f64) -> Self {
        let window_samples = (window_secs * config.sample_rate) as usize;
        let step_samples = (step_secs * config.sample_rate) as usize;
        Self {
            config,
            step_samples: step_samples.max(1),
            window_samples: window_samples.max(4),
        }
    }

    /// Analyze a long seismic record for frequency gliding.
    ///
    /// Returns the time-frequency track and estimated gliding rate.
    pub fn track(&self, signal: &[f64]) -> GlidingResult {
        if signal.len() < self.window_samples {
            return GlidingResult {
                times: Vec::new(),
                frequencies: Vec::new(),
                gliding_rate_hz_per_hour: 0.0,
                is_gliding: false,
            };
        }

        let mut times = Vec::new();
        let mut frequencies = Vec::new();

        let mut pos = 0;
        while pos + self.window_samples <= signal.len() {
            let window = &signal[pos..pos + self.window_samples];
            let freq = dominant_frequency(window, self.config.sample_rate);
            let t = (pos as f64 + self.window_samples as f64 / 2.0) / self.config.sample_rate;
            times.push(t);
            frequencies.push(freq);
            pos += self.step_samples;
        }

        // Compute gliding rate via linear regression on (time, freq) pairs
        let gliding_rate = if frequencies.len() >= 2 {
            linear_regression_slope(&times, &frequencies) * 3600.0 // convert Hz/s to Hz/hour
        } else {
            0.0
        };

        // Detect significant gliding (> 0.1 Hz/hour)
        let is_gliding = gliding_rate.abs() > 0.1;

        GlidingResult {
            times,
            frequencies,
            gliding_rate_hz_per_hour: gliding_rate,
            is_gliding,
        }
    }
}

// ---------------------------------------------------------------------------
// VolcanicEventClassifier
// ---------------------------------------------------------------------------

/// Classifies volcanic seismic events based on spectral and temporal features.
///
/// Classification is based on:
/// - **VT (Volcano-Tectonic)**: Dominant frequency > 5 Hz, impulsive onset,
///   clear P and S arrivals. Generated by brittle rock fracture.
/// - **LP (Long-Period)**: Dominant frequency 0.5-5 Hz, emergent onset,
///   sinusoidal or monochromatic. Generated by fluid pressure transients.
/// - **Hybrid**: Impulsive high-frequency onset followed by LP coda.
/// - **Tremor**: Continuous (> 30 s duration), often harmonic.
#[derive(Debug, Clone)]
pub struct VolcanicEventClassifier {
    config: TremorConfig,
    /// Minimum duration (seconds) to classify as tremor rather than event.
    tremor_min_duration_secs: f64,
}

impl VolcanicEventClassifier {
    /// Create a new classifier.
    pub fn new(config: TremorConfig) -> Self {
        Self {
            config,
            tremor_min_duration_secs: 30.0,
        }
    }

    /// Set the minimum duration for tremor classification.
    pub fn set_tremor_min_duration(&mut self, secs: f64) {
        self.tremor_min_duration_secs = secs;
    }

    /// Classify a seismic event.
    pub fn classify(&self, signal: &[f64]) -> ClassificationResult {
        if signal.len() < 4 {
            return ClassificationResult {
                event_type: VolcanicEventType::Unknown,
                confidence: 0.0,
                dominant_freq: 0.0,
                duration_secs: 0.0,
                peak_amplitude: 0.0,
            };
        }

        let duration = signal.len() as f64 / self.config.sample_rate;
        let peak_amplitude = signal
            .iter()
            .map(|x| x.abs())
            .fold(0.0_f64, f64::max);
        let dom_freq = dominant_frequency(signal, self.config.sample_rate);

        // Spectral ratio: LP band energy / VT band energy
        let sr = spectral_ratio(
            signal,
            self.config.sample_rate,
            self.config.lp_band_low,
            self.config.lp_band_high,
            self.config.vt_band_low,
            self.config.vt_band_high,
        );

        // Onset impulsiveness: ratio of first 10% peak to overall peak
        let onset_len = (signal.len() / 10).max(1);
        let onset_peak = signal[..onset_len]
            .iter()
            .map(|x| x.abs())
            .fold(0.0_f64, f64::max);
        let impulsiveness = if peak_amplitude > 0.0 {
            onset_peak / peak_amplitude
        } else {
            0.0
        };

        // Classification logic
        let (event_type, confidence) = if duration >= self.tremor_min_duration_secs {
            // Long-duration -> Tremor
            (VolcanicEventType::Tremor, 0.8)
        } else if dom_freq >= self.config.vt_band_low && sr < 0.5 {
            // High frequency dominant, low LP/VT ratio -> VT
            let conf = if impulsiveness > 0.5 { 0.9 } else { 0.7 };
            (VolcanicEventType::VT, conf)
        } else if dom_freq <= self.config.lp_band_high && sr > 2.0 {
            // Low frequency dominant, high LP/VT ratio -> LP
            let conf = if impulsiveness < 0.3 { 0.85 } else { 0.65 };
            (VolcanicEventType::LP, conf)
        } else if impulsiveness > 0.5 && sr > 0.5 && sr < 2.0 {
            // Impulsive onset but mixed spectrum -> Hybrid
            (VolcanicEventType::Hybrid, 0.7)
        } else {
            (VolcanicEventType::Unknown, 0.3)
        };

        ClassificationResult {
            event_type,
            confidence,
            dominant_freq: dom_freq,
            duration_secs: duration,
            peak_amplitude,
        }
    }
}

// ---------------------------------------------------------------------------
// EruptionPrecursorDetector
// ---------------------------------------------------------------------------

/// Detects eruption precursor signals from RSAM trends and spectral evolution.
///
/// Monitors:
/// - RSAM ratio relative to baseline (escalating energy release)
/// - RSAM trend (sustained increase suggests magma movement)
/// - Spectral ratio changes (LP energy increase relative to VT)
///
/// Alert levels:
/// - 0 = Background: normal seismic activity
/// - 1 = Elevated: RSAM 2-5x baseline or moderate trend
/// - 2 = High: RSAM 5-10x baseline or strong trend
/// - 3 = Critical: RSAM > 10x baseline with rapid increase
#[derive(Debug, Clone)]
pub struct EruptionPrecursorDetector {
    config: TremorConfig,
    /// Baseline RSAM value for ratio computations.
    baseline_rsam: f64,
    /// Recent RSAM values for trend analysis.
    rsam_history: Vec<f64>,
    /// Maximum number of RSAM windows to keep for trend analysis.
    max_history: usize,
}

impl EruptionPrecursorDetector {
    /// Create a new precursor detector with a known baseline RSAM.
    pub fn new(config: TremorConfig, baseline_rsam: f64) -> Self {
        Self {
            config,
            baseline_rsam: if baseline_rsam > 0.0 {
                baseline_rsam
            } else {
                1.0
            },
            rsam_history: Vec::new(),
            max_history: 144, // 24 hours at 10-min intervals
        }
    }

    /// Update with a new RSAM value and return a precursor assessment.
    pub fn update(&mut self, rsam_value: f64, signal: &[f64]) -> PrecursorResult {
        self.rsam_history.push(rsam_value);
        if self.rsam_history.len() > self.max_history {
            self.rsam_history.remove(0);
        }

        let rsam_ratio = rsam_value / self.baseline_rsam;

        // RSAM trend (slope per window, converted to per hour)
        let rsam_trend = if self.rsam_history.len() >= 3 {
            let slope = linear_slope(&self.rsam_history);
            slope * 3600.0 / self.config.rsam_window_secs
        } else {
            0.0
        };

        // Spectral ratio
        let sr = if signal.len() >= 4 {
            spectral_ratio(
                signal,
                self.config.sample_rate,
                self.config.lp_band_low,
                self.config.lp_band_high,
                self.config.vt_band_low,
                self.config.vt_band_high,
            )
        } else {
            1.0
        };

        // Alert level determination
        let alert_level = if rsam_ratio > 10.0 && rsam_trend > 0.0 {
            3
        } else if rsam_ratio > 5.0 || (rsam_ratio > 3.0 && rsam_trend > 0.5) {
            2
        } else if rsam_ratio > 2.0 || rsam_trend > 0.2 {
            1
        } else {
            0
        };

        let summary = match alert_level {
            0 => "Background seismic activity. No precursory signals.".to_string(),
            1 => format!(
                "Elevated activity: RSAM {:.1}x baseline, trend {:.2}/hr.",
                rsam_ratio, rsam_trend
            ),
            2 => format!(
                "High activity: RSAM {:.1}x baseline, trend {:.2}/hr. Monitor closely.",
                rsam_ratio, rsam_trend
            ),
            3 => format!(
                "CRITICAL: RSAM {:.1}x baseline, trend {:.2}/hr. Eruption may be imminent.",
                rsam_ratio, rsam_trend
            ),
            _ => "Unknown state.".to_string(),
        };

        PrecursorResult {
            rsam_ratio,
            rsam_trend,
            spectral_ratio: sr,
            alert_level,
            summary,
        }
    }

    /// Return current RSAM history for external analysis.
    pub fn rsam_history(&self) -> &[f64] {
        &self.rsam_history
    }

    /// Reset the detector with a new baseline.
    pub fn reset(&mut self, baseline_rsam: f64) {
        self.baseline_rsam = if baseline_rsam > 0.0 {
            baseline_rsam
        } else {
            1.0
        };
        self.rsam_history.clear();
    }
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/// Compute the dominant (peak) frequency of a signal.
///
/// Returns the frequency (Hz) with the highest spectral magnitude,
/// ignoring the DC component (bin 0).
pub fn dominant_frequency(signal: &[f64], sample_rate: f64) -> f64 {
    if signal.len() < 4 {
        return 0.0;
    }
    let fft_size = next_pow2(signal.len()).min(4096);
    let (freqs, mags) = magnitude_spectrum(signal, fft_size, sample_rate);

    // Skip DC bin
    let mut max_idx = 1;
    let mut max_val = 0.0_f64;
    for i in 1..mags.len() {
        if mags[i] > max_val {
            max_val = mags[i];
            max_idx = i;
        }
    }
    freqs[max_idx]
}

/// Compute the spectral energy ratio between two frequency bands.
///
/// Returns energy_in_band1 / energy_in_band2. If band2 energy is zero,
/// returns f64::INFINITY. If band1 energy is zero, returns 0.0.
pub fn spectral_ratio(
    signal: &[f64],
    sample_rate: f64,
    band1_low: f64,
    band1_high: f64,
    band2_low: f64,
    band2_high: f64,
) -> f64 {
    if signal.len() < 4 {
        return 0.0;
    }
    let fft_size = next_pow2(signal.len()).min(4096);
    let (freqs, mags) = magnitude_spectrum(signal, fft_size, sample_rate);

    let mut energy1 = 0.0;
    let mut energy2 = 0.0;

    for i in 0..freqs.len() {
        let f = freqs[i];
        let e = mags[i] * mags[i];
        if f >= band1_low && f <= band1_high {
            energy1 += e;
        }
        if f >= band2_low && f <= band2_high {
            energy2 += e;
        }
    }

    if energy2 > 0.0 {
        energy1 / energy2
    } else if energy1 > 0.0 {
        f64::INFINITY
    } else {
        0.0
    }
}

/// Compute reduced displacement (D_R) for volcanic tremor.
///
/// Reduced displacement normalises the tremor amplitude to a reference
/// distance, allowing comparison between different volcanoes and stations.
///
/// Formula: D_R = A * r / sqrt(2) * sqrt(lambda)
///
/// where:
/// - `rms_amplitude_m`: RMS ground displacement in metres
/// - `distance_m`: Source-to-station distance in metres
/// - `wavelength_m`: Dominant tremor wavelength in metres
///
/// Units: cm^2 (conventional volcanological units)
///
/// Typical values:
/// - < 5 cm^2: minor tremor
/// - 5-20 cm^2: moderate tremor
/// - > 20 cm^2: strong tremor (pre-eruptive)
///
/// Reference: Aki & Koyanagi (1981), Fehler (1983)
pub fn reduced_displacement(
    rms_amplitude_m: f64,
    distance_m: f64,
    wavelength_m: f64,
) -> f64 {
    // D_R in cm^2: A_cm * r_cm / sqrt(2) * sqrt(lambda_cm)
    let a_cm = rms_amplitude_m * 100.0;
    let r_cm = distance_m * 100.0;
    let lambda_cm = wavelength_m * 100.0;
    a_cm * r_cm / (2.0_f64).sqrt() * lambda_cm.sqrt()
}

/// Estimate seismic energy from amplitude and frequency.
///
/// Uses the Gutenberg-Richter energy-magnitude relationship adapted
/// for volcanic signals:
///
/// E = (2 * pi * f)^2 * A^2 * rho * v * S * T
///
/// Simplified version using RMS amplitude:
/// - `rms_amplitude_m`: RMS ground velocity in m/s
/// - `frequency_hz`: Dominant frequency in Hz
/// - `duration_secs`: Event duration in seconds
/// - `density_kg_m3`: Rock density (default ~2700 kg/m^3)
/// - `velocity_m_s`: Seismic wave velocity (default ~3000 m/s for P-wave)
///
/// Returns energy in Joules (approximate).
pub fn seismic_energy(
    rms_amplitude_m_s: f64,
    frequency_hz: f64,
    duration_secs: f64,
    density_kg_m3: f64,
    velocity_m_s: f64,
) -> f64 {
    // E = 2 * pi * r^2 * rho * v * A^2 * T
    // Using a nominal spreading distance of 1 km for a point source
    let r = 1000.0; // reference distance 1 km
    let area = 2.0 * PI * r * r; // hemispherical spreading
    let _omega = 2.0 * PI * frequency_hz;
    area * density_kg_m3 * velocity_m_s * rms_amplitude_m_s * rms_amplitude_m_s * duration_secs
}

/// Compute linear regression slope for equally spaced data points.
///
/// Returns the slope of the best-fit line y = mx + b using least squares.
fn linear_slope(data: &[f64]) -> f64 {
    let n = data.len();
    if n < 2 {
        return 0.0;
    }
    let nf = n as f64;
    let x_mean = (nf - 1.0) / 2.0;
    let y_mean: f64 = data.iter().sum::<f64>() / nf;

    let mut num = 0.0;
    let mut den = 0.0;
    for (i, &y) in data.iter().enumerate() {
        let x = i as f64;
        num += (x - x_mean) * (y - y_mean);
        den += (x - x_mean) * (x - x_mean);
    }
    if den.abs() < 1e-30 {
        return 0.0;
    }
    num / den
}

/// Compute linear regression slope for (x, y) pairs.
fn linear_regression_slope(x: &[f64], y: &[f64]) -> f64 {
    let n = x.len();
    if n < 2 || y.len() < 2 {
        return 0.0;
    }
    let n = n.min(y.len());
    let nf = n as f64;
    let x_mean: f64 = x[..n].iter().sum::<f64>() / nf;
    let y_mean: f64 = y[..n].iter().sum::<f64>() / nf;

    let mut num = 0.0;
    let mut den = 0.0;
    for i in 0..n {
        num += (x[i] - x_mean) * (y[i] - y_mean);
        den += (x[i] - x_mean) * (x[i] - x_mean);
    }
    if den.abs() < 1e-30 {
        return 0.0;
    }
    num / den
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate a synthetic seismic signal with specified frequency components.
    fn make_signal(freqs: &[(f64, f64)], sample_rate: f64, duration_secs: f64) -> Vec<f64> {
        let n = (sample_rate * duration_secs) as usize;
        (0..n)
            .map(|i| {
                let t = i as f64 / sample_rate;
                freqs
                    .iter()
                    .map(|&(f, a)| a * (2.0 * PI * f * t).sin())
                    .sum::<f64>()
            })
            .collect()
    }

    // --- TremorConfig tests ---

    #[test]
    fn test_default_config() {
        let config = TremorConfig::default();
        assert_eq!(config.sample_rate, 100.0);
        assert_eq!(config.rsam_window_secs, 600.0);
        assert_eq!(config.fft_size, 1024);
        assert_eq!(config.min_harmonics, 3);
        assert!((config.harmonic_tolerance - 0.05).abs() < 1e-10);
    }

    #[test]
    fn test_custom_config() {
        let config = TremorConfig {
            sample_rate: 200.0,
            lp_band_low: 1.0,
            lp_band_high: 4.0,
            vt_band_low: 6.0,
            vt_band_high: 20.0,
            rsam_window_secs: 300.0,
            fft_size: 2048,
            min_harmonics: 4,
            harmonic_tolerance: 0.1,
        };
        assert_eq!(config.sample_rate, 200.0);
        assert_eq!(config.fft_size, 2048);
    }

    // --- RsamCalculator tests ---

    #[test]
    fn test_rsam_constant_signal() {
        let config = TremorConfig {
            rsam_window_secs: 1.0,
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let mut rsam = RsamCalculator::new(config);
        let signal = vec![5.0; 300]; // 3 seconds = 3 windows
        let values = rsam.process(&signal);
        assert_eq!(values.len(), 3);
        for v in &values {
            assert!((v - 5.0).abs() < 1e-10);
        }
    }

    #[test]
    fn test_rsam_sinusoidal() {
        let config = TremorConfig {
            rsam_window_secs: 1.0,
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let mut rsam = RsamCalculator::new(config.clone());
        let signal = make_signal(&[(2.0, 100.0)], config.sample_rate, 2.0);
        let values = rsam.process(&signal);
        assert_eq!(values.len(), 2);
        // Mean absolute value of a sine wave = 2*A/pi
        let expected = 2.0 * 100.0 / PI;
        for v in &values {
            assert!((v - expected).abs() < 5.0, "RSAM {v} not near {expected}");
        }
    }

    #[test]
    fn test_rsam_empty_signal() {
        let config = TremorConfig::default();
        let mut rsam = RsamCalculator::new(config);
        let values = rsam.process(&[]);
        assert!(values.is_empty());
    }

    #[test]
    fn test_rsam_ratio() {
        let config = TremorConfig {
            rsam_window_secs: 1.0,
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let mut rsam = RsamCalculator::new(config);
        assert!(rsam.rsam_ratio(10.0).is_none());

        rsam.set_baseline(5.0);
        let ratio = rsam.rsam_ratio(10.0).unwrap();
        assert!((ratio - 2.0).abs() < 1e-10);
    }

    #[test]
    fn test_rsam_trend_increasing() {
        let config = TremorConfig::default();
        let rsam = RsamCalculator::new(config);
        let values = vec![1.0, 2.0, 3.0, 4.0, 5.0];
        let trend = rsam.compute_trend(&values);
        assert!((trend - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_rsam_trend_constant() {
        let config = TremorConfig::default();
        let rsam = RsamCalculator::new(config);
        let values = vec![5.0, 5.0, 5.0, 5.0];
        let trend = rsam.compute_trend(&values);
        assert!(trend.abs() < 1e-10);
    }

    #[test]
    fn test_rsam_window_samples() {
        let config = TremorConfig {
            rsam_window_secs: 10.0,
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let rsam = RsamCalculator::new(config);
        assert_eq!(rsam.window_samples(), 1000);
    }

    // --- HarmonicTremorDetector tests ---

    #[test]
    fn test_harmonic_tremor_with_harmonics() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 1024,
            min_harmonics: 3,
            harmonic_tolerance: 0.08,
            ..TremorConfig::default()
        };
        let mut detector = HarmonicTremorDetector::new(config.clone());
        // Generate a signal with f0=2 Hz and harmonics at 4, 6, 8 Hz
        let signal = make_signal(
            &[(2.0, 100.0), (4.0, 50.0), (6.0, 25.0), (8.0, 12.0)],
            config.sample_rate,
            10.0,
        );
        let result = detector.analyze(&signal);
        assert!(result.is_harmonic);
        assert!(result.fundamental_freq > 1.5 && result.fundamental_freq < 2.5,
            "Fundamental {:.2} not near 2 Hz", result.fundamental_freq);
        assert!(result.harmonic_freqs.len() >= 3);
        assert!(result.quality_factor > 0.0);
    }

    #[test]
    fn test_harmonic_tremor_no_harmonics() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 512,
            min_harmonics: 3,
            ..TremorConfig::default()
        };
        let mut detector = HarmonicTremorDetector::new(config.clone());
        // Single frequency - not enough harmonics
        let signal = make_signal(&[(3.0, 100.0)], config.sample_rate, 5.0);
        let result = detector.analyze(&signal);
        // Single tone should have at most 1 peak
        assert!(!result.is_harmonic || result.harmonic_freqs.len() < 3);
    }

    #[test]
    fn test_harmonic_tremor_empty() {
        let config = TremorConfig::default();
        let mut detector = HarmonicTremorDetector::new(config);
        let result = detector.analyze(&[]);
        assert!(!result.is_harmonic);
        assert_eq!(result.fundamental_freq, 0.0);
    }

    #[test]
    fn test_harmonic_quality_factor() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 1024,
            min_harmonics: 2,
            harmonic_tolerance: 0.08,
            ..TremorConfig::default()
        };
        let mut detector = HarmonicTremorDetector::new(config.clone());
        let signal = make_signal(
            &[(2.0, 100.0), (4.0, 80.0), (6.0, 60.0)],
            config.sample_rate,
            10.0,
        );
        let result = detector.analyze(&signal);
        assert!(result.quality_factor > 0.0 && result.quality_factor <= 1.0);
    }

    // --- FrequencyGlidingTracker tests ---

    #[test]
    fn test_gliding_upward() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 512,
            ..TremorConfig::default()
        };
        let tracker = FrequencyGlidingTracker::new(config.clone(), 5.0, 5.0);
        // Create a signal where frequency increases over time
        let duration = 60.0;
        let n = (config.sample_rate * duration) as usize;
        let mut signal = vec![0.0; n];
        for i in 0..n {
            let t = i as f64 / config.sample_rate;
            // Frequency ramps from 2 Hz to 6 Hz over 60 seconds
            let freq = 2.0 + 4.0 * t / duration;
            signal[i] = 100.0 * (2.0 * PI * freq * t).sin();
        }
        let result = tracker.track(&signal);
        assert!(!result.times.is_empty());
        assert!(!result.frequencies.is_empty());
        // Frequency should generally increase
        assert!(
            result.gliding_rate_hz_per_hour > 0.0,
            "Expected positive gliding rate, got {}",
            result.gliding_rate_hz_per_hour
        );
    }

    #[test]
    fn test_gliding_stable() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 256,
            ..TremorConfig::default()
        };
        let tracker = FrequencyGlidingTracker::new(config.clone(), 2.0, 2.0);
        // Constant frequency signal
        let signal = make_signal(&[(3.0, 100.0)], config.sample_rate, 30.0);
        let result = tracker.track(&signal);
        assert!(!result.is_gliding);
        assert!(
            result.gliding_rate_hz_per_hour.abs() < 5.0,
            "Expected near-zero gliding rate, got {}",
            result.gliding_rate_hz_per_hour
        );
    }

    #[test]
    fn test_gliding_short_signal() {
        let config = TremorConfig {
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let tracker = FrequencyGlidingTracker::new(config, 10.0, 5.0);
        let result = tracker.track(&[1.0, 2.0, 3.0]);
        assert!(result.times.is_empty());
    }

    // --- VolcanicEventClassifier tests ---

    #[test]
    fn test_classify_vt_event() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 512,
            ..TremorConfig::default()
        };
        let classifier = VolcanicEventClassifier::new(config.clone());
        // High-frequency impulsive signal (VT-like)
        let mut signal = vec![0.0; 500]; // 5 seconds
        // Impulsive onset with high-frequency content
        for i in 0..50 {
            let t = i as f64 / config.sample_rate;
            signal[i] = 200.0 * (-t * 10.0).exp() * (2.0 * PI * 10.0 * t).sin();
        }
        // Add high-freq content throughout
        for i in 0..500 {
            let t = i as f64 / config.sample_rate;
            signal[i] += 50.0 * (2.0 * PI * 8.0 * t).sin();
        }
        let result = classifier.classify(&signal);
        assert!(result.dominant_freq > 5.0, "Expected VT freq > 5 Hz, got {}", result.dominant_freq);
        assert!(result.peak_amplitude > 0.0);
        assert!(result.duration_secs > 0.0);
    }

    #[test]
    fn test_classify_lp_event() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 512,
            ..TremorConfig::default()
        };
        let classifier = VolcanicEventClassifier::new(config.clone());
        // Low-frequency emergent signal (LP-like): 1.5 Hz dominant
        let signal = make_signal(&[(1.5, 100.0), (3.0, 30.0)], config.sample_rate, 10.0);
        let result = classifier.classify(&signal);
        assert!(result.dominant_freq <= 5.0, "Expected LP freq <= 5 Hz, got {}", result.dominant_freq);
        assert_eq!(result.event_type, VolcanicEventType::LP);
    }

    #[test]
    fn test_classify_tremor() {
        let config = TremorConfig {
            sample_rate: 100.0,
            fft_size: 512,
            ..TremorConfig::default()
        };
        let mut classifier = VolcanicEventClassifier::new(config.clone());
        classifier.set_tremor_min_duration(10.0);
        // Long-duration signal (tremor-like)
        let signal = make_signal(&[(2.0, 50.0)], config.sample_rate, 60.0);
        let result = classifier.classify(&signal);
        assert_eq!(result.event_type, VolcanicEventType::Tremor);
        assert!(result.confidence >= 0.7);
    }

    #[test]
    fn test_classify_empty() {
        let config = TremorConfig::default();
        let classifier = VolcanicEventClassifier::new(config);
        let result = classifier.classify(&[]);
        assert_eq!(result.event_type, VolcanicEventType::Unknown);
        assert_eq!(result.confidence, 0.0);
    }

    #[test]
    fn test_classify_returns_duration() {
        let config = TremorConfig {
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let classifier = VolcanicEventClassifier::new(config);
        let signal = vec![1.0; 500];
        let result = classifier.classify(&signal);
        assert!((result.duration_secs - 5.0).abs() < 0.01);
    }

    // --- EruptionPrecursorDetector tests ---

    #[test]
    fn test_precursor_background() {
        let config = TremorConfig {
            sample_rate: 100.0,
            rsam_window_secs: 1.0,
            ..TremorConfig::default()
        };
        let mut detector = EruptionPrecursorDetector::new(config.clone(), 10.0);
        let signal = make_signal(&[(2.0, 10.0)], config.sample_rate, 1.0);
        let result = detector.update(10.0, &signal);
        assert_eq!(result.alert_level, 0);
        assert!((result.rsam_ratio - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_precursor_elevated() {
        let config = TremorConfig {
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let mut detector = EruptionPrecursorDetector::new(config.clone(), 10.0);
        let signal = make_signal(&[(2.0, 10.0)], config.sample_rate, 1.0);
        // RSAM 3x baseline
        let result = detector.update(30.0, &signal);
        assert!(result.alert_level >= 1);
        assert!((result.rsam_ratio - 3.0).abs() < 1e-10);
    }

    #[test]
    fn test_precursor_critical() {
        let config = TremorConfig {
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let mut detector = EruptionPrecursorDetector::new(config.clone(), 10.0);
        let signal = make_signal(&[(2.0, 10.0)], config.sample_rate, 1.0);
        // Feed increasing RSAM values to build a positive trend
        for i in 1..=10 {
            detector.update(10.0 * i as f64, &signal);
        }
        // RSAM 15x baseline with history of increase
        let result = detector.update(150.0, &signal);
        assert_eq!(result.alert_level, 3);
        assert!(result.rsam_ratio > 10.0);
        assert!(result.summary.contains("CRITICAL"));
    }

    #[test]
    fn test_precursor_reset() {
        let config = TremorConfig::default();
        let mut detector = EruptionPrecursorDetector::new(config.clone(), 10.0);
        let signal = vec![1.0; 100];
        detector.update(20.0, &signal);
        assert_eq!(detector.rsam_history().len(), 1);
        detector.reset(5.0);
        assert!(detector.rsam_history().is_empty());
    }

    #[test]
    fn test_precursor_history_limit() {
        let config = TremorConfig {
            sample_rate: 100.0,
            ..TremorConfig::default()
        };
        let mut detector = EruptionPrecursorDetector::new(config, 10.0);
        let signal = vec![1.0; 100];
        for i in 0..200 {
            detector.update(i as f64, &signal);
        }
        assert!(detector.rsam_history().len() <= 144);
    }

    // --- Helper function tests ---

    #[test]
    fn test_dominant_frequency_pure_tone() {
        let sr = 100.0;
        let signal = make_signal(&[(5.0, 100.0)], sr, 10.0);
        let freq = dominant_frequency(&signal, sr);
        assert!(
            (freq - 5.0).abs() < 0.5,
            "Expected ~5 Hz, got {freq}"
        );
    }

    #[test]
    fn test_dominant_frequency_multi_tone() {
        let sr = 100.0;
        // 3 Hz at amplitude 100 should dominate over 7 Hz at amplitude 20
        let signal = make_signal(&[(3.0, 100.0), (7.0, 20.0)], sr, 10.0);
        let freq = dominant_frequency(&signal, sr);
        assert!(
            (freq - 3.0).abs() < 1.0,
            "Expected ~3 Hz dominant, got {freq}"
        );
    }

    #[test]
    fn test_dominant_frequency_short() {
        let freq = dominant_frequency(&[1.0, 2.0], 100.0);
        assert_eq!(freq, 0.0);
    }

    #[test]
    fn test_spectral_ratio_lp_dominant() {
        let sr = 100.0;
        // Strong LP (2 Hz) signal with weak VT (8 Hz)
        let signal = make_signal(&[(2.0, 100.0), (8.0, 10.0)], sr, 10.0);
        let ratio = spectral_ratio(&signal, sr, 0.5, 5.0, 5.0, 15.0);
        assert!(ratio > 1.0, "Expected LP/VT ratio > 1, got {ratio}");
    }

    #[test]
    fn test_spectral_ratio_vt_dominant() {
        let sr = 100.0;
        // Strong VT (8 Hz) signal with weak LP (2 Hz)
        let signal = make_signal(&[(2.0, 10.0), (8.0, 100.0)], sr, 10.0);
        let ratio = spectral_ratio(&signal, sr, 0.5, 5.0, 5.0, 15.0);
        assert!(ratio < 1.0, "Expected LP/VT ratio < 1, got {ratio}");
    }

    #[test]
    fn test_spectral_ratio_empty() {
        let ratio = spectral_ratio(&[], 100.0, 0.5, 5.0, 5.0, 15.0);
        assert_eq!(ratio, 0.0);
    }

    #[test]
    fn test_reduced_displacement() {
        // Typical values: A=1e-6 m, r=5000 m, lambda=1500 m
        let dr = reduced_displacement(1e-6, 5000.0, 1500.0);
        assert!(dr > 0.0);
        // Check scaling: doubling amplitude doubles D_R
        let dr2 = reduced_displacement(2e-6, 5000.0, 1500.0);
        assert!((dr2 / dr - 2.0).abs() < 1e-6);
    }

    #[test]
    fn test_reduced_displacement_zero_amplitude() {
        let dr = reduced_displacement(0.0, 5000.0, 1500.0);
        assert_eq!(dr, 0.0);
    }

    #[test]
    fn test_seismic_energy_positive() {
        let energy = seismic_energy(1e-6, 2.0, 60.0, 2700.0, 3000.0);
        assert!(energy > 0.0);
    }

    #[test]
    fn test_seismic_energy_scales_with_amplitude() {
        let e1 = seismic_energy(1e-6, 2.0, 60.0, 2700.0, 3000.0);
        let e2 = seismic_energy(2e-6, 2.0, 60.0, 2700.0, 3000.0);
        // Energy scales as amplitude^2
        assert!((e2 / e1 - 4.0).abs() < 1e-6);
    }

    #[test]
    fn test_seismic_energy_scales_with_duration() {
        let e1 = seismic_energy(1e-6, 2.0, 60.0, 2700.0, 3000.0);
        let e2 = seismic_energy(1e-6, 2.0, 120.0, 2700.0, 3000.0);
        // Energy scales linearly with duration
        assert!((e2 / e1 - 2.0).abs() < 1e-6);
    }

    // --- Internal helper tests ---

    #[test]
    fn test_linear_slope_increasing() {
        let data = vec![0.0, 1.0, 2.0, 3.0, 4.0];
        let slope = linear_slope(&data);
        assert!((slope - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_linear_slope_decreasing() {
        let data = vec![4.0, 3.0, 2.0, 1.0, 0.0];
        let slope = linear_slope(&data);
        assert!((slope + 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_linear_regression_slope() {
        let x = vec![0.0, 1.0, 2.0, 3.0];
        let y = vec![1.0, 3.0, 5.0, 7.0];
        let slope = linear_regression_slope(&x, &y);
        assert!((slope - 2.0).abs() < 1e-10);
    }

    #[test]
    fn test_next_pow2() {
        assert_eq!(next_pow2(1), 1);
        assert_eq!(next_pow2(3), 4);
        assert_eq!(next_pow2(1024), 1024);
        assert_eq!(next_pow2(1025), 2048);
    }

    #[test]
    fn test_fft_inplace_known_signal() {
        // DC signal of all 1s, length 4
        let mut real = vec![1.0, 1.0, 1.0, 1.0];
        let mut imag = vec![0.0, 0.0, 0.0, 0.0];
        fft_inplace(&mut real, &mut imag);
        // DC bin should be 4.0, all others 0.0
        assert!((real[0] - 4.0).abs() < 1e-10);
        assert!(real[1].abs() < 1e-10);
        assert!(real[2].abs() < 1e-10);
        assert!(real[3].abs() < 1e-10);
    }

    #[test]
    fn test_volcanic_event_type_equality() {
        assert_eq!(VolcanicEventType::VT, VolcanicEventType::VT);
        assert_ne!(VolcanicEventType::VT, VolcanicEventType::LP);
        assert_ne!(VolcanicEventType::Tremor, VolcanicEventType::Hybrid);
    }
}
