#-----------------------------------------------------------------------------
# PYNQ-Z2 Board Constraints for R4W IP Cores
# Xilinx XC7Z020-1CLG400C
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# Clock Constraints
#-----------------------------------------------------------------------------

# PS FCLK0 - Primary fabric clock (100 MHz from PS)
# This clock is generated by the PS and distributed to PL
# The PS automatically configures this, but we constrain it for timing analysis
create_clock -period 10.000 -name FCLK_CLK0 [get_pins design_1_i/processing_system7_0/FCLK_CLK0]

# Additional clock for high-speed processing if needed (can be enabled via PS)
# create_clock -period 5.000 -name FCLK_CLK1 [get_pins design_1_i/processing_system7_0/FCLK_CLK1]

#-----------------------------------------------------------------------------
# False Paths
#-----------------------------------------------------------------------------

# AXI reset is async, treat as false path for timing
set_false_path -from [get_pins design_1_i/processing_system7_0/FCLK_RESET0_N]

#-----------------------------------------------------------------------------
# Input/Output Delays for PL I/O (if using external ports)
#-----------------------------------------------------------------------------

# If connecting to external ADC/DAC on PMOD ports, add constraints here:
# set_input_delay -clock FCLK_CLK0 -max 2.0 [get_ports {pmod_*}]
# set_output_delay -clock FCLK_CLK0 -max 2.0 [get_ports {pmod_*}]

#-----------------------------------------------------------------------------
# PMOD Constraints (if using PMOD connectors for external I/O)
#-----------------------------------------------------------------------------

# PMODA - Top row (directly adjacent to edge)
# set_property PACKAGE_PIN Y18  [get_ports {pmoda[0]}]; # JA1_P
# set_property PACKAGE_PIN Y19  [get_ports {pmoda[1]}]; # JA1_N
# set_property PACKAGE_PIN Y16  [get_ports {pmoda[2]}]; # JA2_P
# set_property PACKAGE_PIN Y17  [get_ports {pmoda[3]}]; # JA2_N
# set_property PACKAGE_PIN U18  [get_ports {pmoda[4]}]; # JA3_P
# set_property PACKAGE_PIN U19  [get_ports {pmoda[5]}]; # JA3_N
# set_property PACKAGE_PIN W18  [get_ports {pmoda[6]}]; # JA4_P
# set_property PACKAGE_PIN W19  [get_ports {pmoda[7]}]; # JA4_N
# set_property IOSTANDARD LVCMOS33 [get_ports {pmoda[*]}]

# PMODB - Bottom row
# set_property PACKAGE_PIN W14  [get_ports {pmodb[0]}]; # JB1_P
# set_property PACKAGE_PIN Y14  [get_ports {pmodb[1]}]; # JB1_N
# set_property PACKAGE_PIN T11  [get_ports {pmodb[2]}]; # JB2_P
# set_property PACKAGE_PIN T10  [get_ports {pmodb[3]}]; # JB2_N
# set_property PACKAGE_PIN V16  [get_ports {pmodb[4]}]; # JB3_P
# set_property PACKAGE_PIN W16  [get_ports {pmodb[5]}]; # JB3_N
# set_property PACKAGE_PIN V12  [get_ports {pmodb[6]}]; # JB4_P
# set_property PACKAGE_PIN W13  [get_ports {pmodb[7]}]; # JB4_N
# set_property IOSTANDARD LVCMOS33 [get_ports {pmodb[*]}]

#-----------------------------------------------------------------------------
# Arduino/ChipKit Shield Pins (directly accessible GPIO)
#-----------------------------------------------------------------------------

# Arduino analog pins (directly accessible on header)
# set_property PACKAGE_PIN F19 [get_ports {arduino_a0}]; # AR_AN0
# set_property PACKAGE_PIN F20 [get_ports {arduino_a1}]; # AR_AN1
# set_property PACKAGE_PIN B20 [get_ports {arduino_a2}]; # AR_AN2
# set_property PACKAGE_PIN A20 [get_ports {arduino_a3}]; # AR_AN3
# set_property IOSTANDARD LVCMOS33 [get_ports {arduino_a*}]

#-----------------------------------------------------------------------------
# LEDs and Buttons (directly accessible on PYNQ-Z2 board)
#-----------------------------------------------------------------------------

# User LEDs (accent LEDs near edge, accent accent green and blue)
# set_property PACKAGE_PIN R14 [get_ports {led[0]}]; # LD0
# set_property PACKAGE_PIN P14 [get_ports {led[1]}]; # LD1
# set_property PACKAGE_PIN N16 [get_ports {led[2]}]; # LD2
# set_property PACKAGE_PIN M14 [get_ports {led[3]}]; # LD3
# set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

# RGB LED 4 (accent LED controlled by PL)
# set_property PACKAGE_PIN L15 [get_ports {led4_b}]; # LED4_B
# set_property PACKAGE_PIN G17 [get_ports {led4_g}]; # LED4_G
# set_property PACKAGE_PIN N15 [get_ports {led4_r}]; # LED4_R
# set_property IOSTANDARD LVCMOS33 [get_ports {led4_*}]

# RGB LED 5 (accent LED controlled by PL)
# set_property PACKAGE_PIN G14 [get_ports {led5_b}]; # LED5_B
# set_property PACKAGE_PIN L14 [get_ports {led5_g}]; # LED5_G
# set_property PACKAGE_PIN M15 [get_ports {led5_r}]; # LED5_R
# set_property IOSTANDARD LVCMOS33 [get_ports {led5_*}]

# User Buttons
# set_property PACKAGE_PIN D19 [get_ports {btn[0]}]; # BTN0
# set_property PACKAGE_PIN D20 [get_ports {btn[1]}]; # BTN1
# set_property PACKAGE_PIN L20 [get_ports {btn[2]}]; # BTN2
# set_property PACKAGE_PIN L19 [get_ports {btn[3]}]; # BTN3
# set_property IOSTANDARD LVCMOS33 [get_ports {btn[*]}]

# User Switches
# set_property PACKAGE_PIN M20 [get_ports {sw[0]}]; # SW0
# set_property PACKAGE_PIN M19 [get_ports {sw[1]}]; # SW1
# set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]

#-----------------------------------------------------------------------------
# Timing Exceptions
#-----------------------------------------------------------------------------

# Relax timing on slow control paths
# set_multicycle_path 2 -setup -from [get_clocks FCLK_CLK0] -to [get_clocks FCLK_CLK0] -through [get_pins -hier -filter {NAME =~ */ctrl_reg*/Q}]

#-----------------------------------------------------------------------------
# Power Optimization
#-----------------------------------------------------------------------------

# Enable block RAM power optimization
set_property BLOCK_POWER_OPT true [current_design]

#-----------------------------------------------------------------------------
# DRC Waivers
#-----------------------------------------------------------------------------

# Waive DRC for unused PS pins (common in designs using only subset of PS features)
# set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

#-----------------------------------------------------------------------------
# Bitstream Settings
#-----------------------------------------------------------------------------

# Enable bitstream compression (reduces file size by ~50%)
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

# Set configuration voltage
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
